# Generated by Django 5.0 on 2026-03-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0036_add_inventory_scheduling_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(
                    choices=[
                        ('low', 'Low'),
                        ('normal', 'Normal'),
                        ('high', 'High'),
                        ('urgent', 'Urgent'),
                    ],
                    default='normal',
                    max_length=10,
                )),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(
                    choices=[
                        ('none', 'None (one-time)'),
                        ('daily', 'Daily'),
                        ('weekly', 'Weekly'),
                        ('biweekly', 'Bi-weekly'),
                        ('monthly', 'Monthly'),
                        ('quarterly', 'Quarterly'),
                        ('custom', 'Custom'),
                    ],
                    default='none',
                    max_length=20,
                )),
                ('recurrence_interval_days', models.IntegerField(
                    blank=True,
                    null=True,
                    help_text='Number of days between occurrences (used when recurrence=custom)',
                )),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('in_progress', 'In Progress'),
                        ('completed', 'Completed'),
                        ('overdue', 'Overdue'),
                        ('cancelled', 'Cancelled'),
                        ('skipped', 'Skipped'),
                    ],
                    default='pending',
                    max_length=20,
                )),
                ('require_all_signoffs', models.BooleanField(
                    default=False,
                    help_text='Require all assigned users to sign off before marking complete',
                )),
                ('is_template', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scheduled_tasks',
                    to='core.organization',
                )),
                ('parent_task', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='child_instances',
                    to='scheduling.scheduledtask',
                )),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_tasks',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('completed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='completed_tasks',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('tags', models.ManyToManyField(blank=True, related_name='scheduled_tasks', to='core.tag')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'db_table': 'scheduled_tasks',
                'ordering': ['due_date', 'priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='task_assignments',
                    to='scheduling.scheduledtask',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='task_assignments',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'db_table': 'task_assignments',
            },
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='assigned_to',
            field=models.ManyToManyField(
                blank=True,
                related_name='assigned_tasks',
                through='scheduling.TaskAssignment',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'user')},
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='scheduling.scheduledtask',
                )),
                ('author', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='task_comments',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'db_table': 'task_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
