"""
Integrations app tests.

Currently focused on the Workstream 8 distributor surface (DistributorConnection
+ Ingram Xvantage adapter + webhook signature verification). The PSA/RMM
sync paths are exercised in their own debug commands and via the upstream
provider sandboxes; we don't mock those here.
"""
from __future__ import annotations

import hashlib
import hmac
import json

from django.test import TestCase, override_settings

from core.models import Organization
from .models import DistributorConnection, DistributorWebhookEvent


class DistributorConnectionModelTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP')

    def test_credential_round_trip_is_encrypted(self):
        conn = DistributorConnection.objects.create(
            organization=self.org,
            provider_type='ingram_xvantage',
            name='Ingram Sandbox',
        )
        conn.set_credentials({
            'client_id': 'abc123',
            'client_secret': 'shhh',
            'customer_number': 'C0001',
        })
        conn.save()

        reloaded = DistributorConnection.objects.get(pk=conn.pk)
        creds = reloaded.get_credentials()
        self.assertEqual(creds['client_id'], 'abc123')
        self.assertEqual(creds['client_secret'], 'shhh')
        self.assertEqual(creds['customer_number'], 'C0001')
        # Ciphertext must not contain the plaintext secret.
        self.assertNotIn('shhh', reloaded.encrypted_credentials)

    def test_webhook_token_is_autogenerated_and_unique(self):
        c1 = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage', name='A')
        c2 = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage', name='B')
        self.assertTrue(c1.webhook_token)
        self.assertTrue(c2.webhook_token)
        self.assertNotEqual(c1.webhook_token, c2.webhook_token)
        # token_urlsafe(32) → ~43 chars, base64url-safe alphabet
        self.assertGreaterEqual(len(c1.webhook_token), 32)

    def test_webhook_secret_round_trips(self):
        conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage', name='X')
        conn.set_webhook_secret('very-secret-hmac-key')
        conn.save()
        reloaded = DistributorConnection.objects.get(pk=conn.pk)
        self.assertEqual(reloaded.get_webhook_secret(), 'very-secret-hmac-key')
        self.assertNotIn('very-secret', reloaded.encrypted_webhook_secret)


class IngramAdapterTests(TestCase):
    """
    The provider does no live HTTP at construction time, so we can build
    one and exercise its parser/signature logic without mocking out
    requests. Network-touching methods are exercised against the
    Ingram sandbox in manual QA.
    """

    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP')
        self.conn = DistributorConnection.objects.create(
            organization=self.org,
            provider_type='ingram_xvantage',
            name='Ingram',
            base_url='',  # exercise the DEFAULT_BASE_URL fallback
        )
        self.conn.set_credentials({'client_id': 'cid', 'client_secret': 'csec',
                                   'customer_number': 'C-1'})
        self.conn.set_webhook_secret('hmac-secret')
        self.conn.save()

    def _provider(self):
        from .providers.distributors import get_distributor_provider
        return get_distributor_provider(self.conn)

    def test_provider_resolution(self):
        p = self._provider()
        self.assertIsNotNone(p)
        self.assertEqual(p.provider_name, 'Ingram Micro Xvantage')

    def test_default_base_url_filled_when_blank(self):
        # Reload the connection — the provider __init__ writes the default
        # back onto connection.base_url before BaseProvider's SSRF check.
        p = self._provider()
        self.assertTrue(p.base_url)
        self.assertIn('ingrammicro.com', p.base_url)

    def test_handle_webhook_valid_signature(self):
        p = self._provider()
        body = json.dumps({'eventType': 'order.shipped', 'order_id': 'X1'}).encode()
        sig = hmac.new(b'hmac-secret', body, hashlib.sha256).hexdigest()
        result = p.handle_webhook(
            headers={'X-Ingram-Signature': f'sha256={sig}'}, raw_body=body
        )
        self.assertTrue(result['signature_valid'])
        self.assertEqual(result['event_type'], 'order.shipped')
        self.assertEqual(result['parsed']['order_id'], 'X1')

    def test_handle_webhook_invalid_signature(self):
        p = self._provider()
        body = b'{"eventType":"order.shipped"}'
        result = p.handle_webhook(
            headers={'X-Ingram-Signature': 'sha256=deadbeef'}, raw_body=body
        )
        self.assertFalse(result['signature_valid'])

    def test_handle_webhook_missing_signature(self):
        p = self._provider()
        result = p.handle_webhook(headers={}, raw_body=b'{}')
        self.assertFalse(result['signature_valid'])

    def test_handle_webhook_malformed_body(self):
        p = self._provider()
        result = p.handle_webhook(headers={}, raw_body=b'not-json')
        self.assertFalse(result['signature_valid'])
        self.assertEqual(result['parsed'], {})


class Pax8AdapterTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP P8')
        self.conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='pax8',
            name='Pax8', base_url='',
        )
        self.conn.set_credentials({'client_id': 'cid', 'client_secret': 'csec'})
        self.conn.set_webhook_secret('px-secret')
        self.conn.save()

    def test_provider_resolves_and_uses_default_url(self):
        from .providers.distributors import get_distributor_provider
        p = get_distributor_provider(self.conn)
        self.assertIsNotNone(p)
        self.assertEqual(p.provider_name, 'Pax8')
        self.assertIn('pax8.com', p.base_url)

    def test_pax8_webhook_valid_signature(self):
        from .providers.distributors import get_distributor_provider
        p = get_distributor_provider(self.conn)
        body = json.dumps({'eventType': 'subscription.created'}).encode()
        sig = hmac.new(b'px-secret', body, hashlib.sha256).hexdigest()
        result = p.handle_webhook(
            headers={'X-Pax8-Signature': sig}, raw_body=body
        )
        self.assertTrue(result['signature_valid'])
        self.assertEqual(result['event_type'], 'subscription.created')


class TDSynnexAdapterTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP TDS')
        self.conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='synnex',
            name='TD Synnex', base_url='',
        )
        self.conn.set_credentials({'client_id': 'cid', 'client_secret': 'csec',
                                   'customer_number': 'CN1'})
        self.conn.set_webhook_secret('tds-secret')
        self.conn.save()

    def test_provider_resolves_and_uses_default_url(self):
        from .providers.distributors import get_distributor_provider
        p = get_distributor_provider(self.conn)
        self.assertIsNotNone(p)
        self.assertEqual(p.provider_name, 'TD Synnex')
        self.assertIn('tdsynnex.com', p.base_url)

    def test_synnex_webhook_valid_signature(self):
        from .providers.distributors import get_distributor_provider
        p = get_distributor_provider(self.conn)
        body = json.dumps({'eventType': 'order.shipped'}).encode()
        sig = hmac.new(b'tds-secret', body, hashlib.sha256).hexdigest()
        result = p.handle_webhook(
            headers={'X-TDS-Signature': sig}, raw_body=body
        )
        self.assertTrue(result['signature_valid'])
        self.assertEqual(result['event_type'], 'order.shipped')


@override_settings(SECURE_SSL_REDIRECT=False)
class DistributorWebhookEndpointTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP')
        self.conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage',
            name='Ingram', is_active=True,
        )
        self.conn.set_webhook_secret('topsecret')
        self.conn.save()

    def test_unknown_token_returns_404(self):
        resp = self.client.post(
            '/integrations/distributors/webhooks/not-a-real-token/',
            data=b'{}', content_type='application/json',
        )
        self.assertEqual(resp.status_code, 404)
        self.assertEqual(DistributorWebhookEvent.objects.count(), 0)

    def test_valid_signature_records_event(self):
        body = json.dumps({'eventType': 'order.delivered'}).encode()
        sig = hmac.new(b'topsecret', body, hashlib.sha256).hexdigest()
        url = f'/integrations/distributors/webhooks/{self.conn.webhook_token}/'
        resp = self.client.post(
            url, data=body, content_type='application/json',
            HTTP_X_INGRAM_SIGNATURE=f'sha256={sig}',
        )
        self.assertEqual(resp.status_code, 200)
        event = DistributorWebhookEvent.objects.get(connection=self.conn)
        self.assertTrue(event.signature_valid)
        self.assertEqual(event.event_type, 'order.delivered')
        self.assertTrue(event.processed)

    def test_invalid_signature_recorded_but_processed_true(self):
        # The webhook endpoint always records — signature_valid false flags it.
        url = f'/integrations/distributors/webhooks/{self.conn.webhook_token}/'
        resp = self.client.post(
            url, data=b'{"eventType":"x"}', content_type='application/json',
            HTTP_X_INGRAM_SIGNATURE='sha256=00',
        )
        self.assertEqual(resp.status_code, 200)
        event = DistributorWebhookEvent.objects.get(connection=self.conn)
        self.assertFalse(event.signature_valid)


class ConnectionStatusHelperTests(TestCase):
    """`connection_status()` powers the integration tiles + list rows."""

    def setUp(self):
        from .status import connection_status  # noqa: F401 — sanity import
        self.org = Organization.objects.create(name='ConnStatus Org')

    def _make(self, **kwargs):
        defaults = dict(
            organization=self.org,
            provider_type='ingram_xvantage',
            name='Status Test',
        )
        defaults.update(kwargs)
        return DistributorConnection.objects.create(**defaults)

    def test_inactive_connection_is_off(self):
        from .status import connection_status
        conn = self._make(is_active=False)
        result = connection_status(conn)
        self.assertEqual(result['state'], 'off')
        self.assertEqual(result['label'], 'OFF')

    def test_sync_disabled_connection_is_off(self):
        from .status import connection_status
        conn = self._make(is_active=True, sync_enabled=False)
        result = connection_status(conn)
        self.assertEqual(result['state'], 'off')

    def test_last_error_means_broken(self):
        from .status import connection_status
        conn = self._make(last_error='401 Unauthorized — token expired.')
        result = connection_status(conn)
        self.assertEqual(result['state'], 'broken')
        self.assertEqual(result['label'], 'ON · Broken')
        self.assertIn('401', result['tooltip'])

    def test_error_status_string_means_broken(self):
        from .status import connection_status
        conn = self._make(last_sync_status='error')
        result = connection_status(conn)
        self.assertEqual(result['state'], 'broken')

    def test_recent_ok_sync_means_working(self):
        from django.utils import timezone
        from .status import connection_status
        conn = self._make(
            last_sync_status='ok',
            last_sync_at=timezone.now(),
        )
        result = connection_status(conn)
        self.assertEqual(result['state'], 'working')
        self.assertEqual(result['label'], 'ON · Working')

    def test_enabled_but_never_synced_is_unknown(self):
        from .status import connection_status
        conn = self._make()  # is_active default True, sync_enabled default True
        result = connection_status(conn)
        self.assertEqual(result['state'], 'unknown')

    def test_long_error_is_truncated_in_tooltip(self):
        from .status import connection_status
        conn = self._make(last_error='X' * 800)
        result = connection_status(conn)
        self.assertEqual(result['state'], 'broken')
        self.assertLessEqual(len(result['tooltip']), 240)
        self.assertTrue(result['tooltip'].endswith('...'))


class IntegrationListViewLogicTests(TestCase):
    """
    Exercise the integration_list view's collection / filter / view-mode logic
    without going through the full auth/middleware/2FA stack — the project
    middleware redirects to 2FA setup, which would obscure what we're testing.
    We patch get_request_organization and call the view directly.
    """

    def setUp(self):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        self.org = Organization.objects.create(name='ListView Org')
        self.user = User.objects.create_user(
            username='list_view_user', email='lv@lv.com', password='x',
            is_staff=True, is_superuser=True,
        )

    def _call(self, url):
        from unittest import mock
        from django.test import RequestFactory
        rf = RequestFactory()
        req = rf.get(url)
        req.user = self.user
        with mock.patch('integrations.views.get_request_organization', return_value=self.org):
            from integrations.views import integration_list
            return integration_list(req)

    def _seed_one(self):
        DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage',
            name='Seed Conn')

    def test_tile_mode_default(self):
        self._seed_one()
        resp = self._call('/integrations/')
        self.assertEqual(resp.status_code, 200)
        self.assertIn(b'integration-tile-grid', resp.content)

    def test_list_mode_renders_table(self):
        self._seed_one()
        resp = self._call('/integrations/?view=list')
        self.assertEqual(resp.status_code, 200)
        self.assertIn(b'table-light', resp.content)

    def test_search_filters_results(self):
        DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage',
            name='Findable Ingram')
        DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage',
            name='Hidden Other')
        resp = self._call('/integrations/?q=findable')
        self.assertEqual(resp.status_code, 200)
        self.assertIn(b'Findable Ingram', resp.content)
        self.assertNotIn(b'Hidden Other', resp.content)


# ---------------------------------------------------------------------------
# Phase 27 v2 — Accounting audit log
# ---------------------------------------------------------------------------

from django.conf import settings as _django_settings
from django.test import Client

_AUDIT_TEST_MIDDLEWARE = [
    m for m in _django_settings.MIDDLEWARE
    if 'Enforce2FAMiddleware' not in m and 'AxesMiddleware' not in m
]


@override_settings(MIDDLEWARE=_AUDIT_TEST_MIDDLEWARE, SECURE_SSL_REDIRECT=False)
class AccountingAuditLogTests(TestCase):
    def setUp(self):
        from django.contrib.auth import get_user_model
        from .models import AccountingConnection
        User = get_user_model()
        self.org = Organization.objects.create(name='AuditCo')
        self.user = User.objects.create_user(
            username='audit_admin', email='aa@aa.com', password='x',
            is_staff=True, is_superuser=True,
        )
        self.conn = AccountingConnection.objects.create(
            organization=self.org, provider_type='quickbooks_online',
            name='QBO-test', is_active=True, sync_enabled=False,
        )
        self.client = Client()
        self.client.force_login(self.user)
        s = self.client.session
        s['2fa_prompted'] = True
        s['current_organization_id'] = self.org.id
        s.save()

    def test_helper_writes_a_row(self):
        from .models import AccountingAuditLog
        from .providers.accounting.base import log_accounting_call
        log_accounting_call(
            connection=self.conn, action='push_invoice',
            resource_type='invoice', resource_id=42,
            external_id='qbo-99', success=True, http_status=200,
            request_summary='lines=2', response_summary='ok',
        )
        row = AccountingAuditLog.objects.get()
        self.assertEqual(row.organization, self.org)
        self.assertEqual(row.connection, self.conn)
        self.assertEqual(row.provider_type, 'quickbooks_online')
        self.assertEqual(row.action, 'push_invoice')
        self.assertEqual(row.resource_id, '42')
        self.assertEqual(row.external_id, 'qbo-99')
        self.assertTrue(row.success)
        self.assertEqual(row.http_status, 200)

    def test_helper_truncates_long_strings(self):
        from .models import AccountingAuditLog
        from .providers.accounting.base import log_accounting_call
        long = 'X' * 1000
        log_accounting_call(
            connection=self.conn, action='push_invoice',
            success=False, error_message=long,
            request_summary=long, response_summary=long,
        )
        row = AccountingAuditLog.objects.get()
        self.assertEqual(len(row.error_message), 500)
        self.assertEqual(len(row.request_summary), 500)
        self.assertEqual(len(row.response_summary), 500)

    def test_view_renders_rows(self):
        from .providers.accounting.base import log_accounting_call
        log_accounting_call(
            connection=self.conn, action='push_invoice',
            resource_type='invoice', resource_id=7,
            external_id='qbo-1', success=True, http_status=200,
        )
        log_accounting_call(
            connection=self.conn, action='push_invoice',
            resource_type='invoice', resource_id=8,
            success=False, http_status=400,
            error_message='HTTP 400: bad payload',
        )
        resp = self.client.get(f'/integrations/accounting/{self.conn.pk}/audit-log/')
        self.assertEqual(resp.status_code, 200)
        body = resp.content.decode()
        self.assertIn('invoice#7', body)
        self.assertIn('invoice#8', body)
        self.assertIn('HTTP 400: bad payload', body)

    def test_view_filter_failures_only(self):
        from .providers.accounting.base import log_accounting_call
        log_accounting_call(connection=self.conn, action='push_invoice',
                            resource_type='invoice', resource_id=10, success=True)
        log_accounting_call(connection=self.conn, action='push_invoice',
                            resource_type='invoice', resource_id=11, success=False,
                            error_message='boom')
        resp = self.client.get(f'/integrations/accounting/{self.conn.pk}/audit-log/?ok=fail')
        self.assertEqual(resp.status_code, 200)
        body = resp.content.decode()
        self.assertIn('invoice#11', body)
        self.assertNotIn('invoice#10', body)

    def test_qbo_push_invoice_logs_on_failure(self):
        """The QBO provider's _api shortcut bails before any HTTP call when
        no realm_id is configured. We use that to drive the failure path of
        push_invoice without mocking, then assert an audit row was written."""
        from unittest import mock
        from .providers.accounting.quickbooks_online import QuickBooksOnlineProvider
        from .models import AccountingAuditLog

        # Stub out the invoice/customer model surface enough that the provider
        # method runs without DB or network. The point is to verify the audit
        # write — not the QBO API surface.
        provider = QuickBooksOnlineProvider(self.conn)
        fake_invoice = mock.MagicMock()
        fake_invoice.pk = 99
        fake_invoice.invoice_number = 'INV-99'
        fake_invoice.client_org = mock.MagicMock(name='client_org')
        # Force _ensure_customer to raise — that hits the first failure exit
        # of push_invoice, which writes an audit row.
        with mock.patch.object(provider, '_ensure_customer',
                               side_effect=RuntimeError('no creds')):
            result = provider.push_invoice(fake_invoice)
        self.assertFalse(result['success'])
        row = AccountingAuditLog.objects.get()
        self.assertEqual(row.action, 'push_invoice')
        self.assertFalse(row.success)
        self.assertIn('no creds', row.error_message)
        self.assertEqual(row.resource_id, '99')


@override_settings(MIDDLEWARE=_AUDIT_TEST_MIDDLEWARE, SECURE_SSL_REDIRECT=False)
class DistributorStockCheckTests(TestCase):
    """Phase 13 v10 (v3.17.272): cross-distributor stock check view."""

    def setUp(self):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        self.org = Organization.objects.create(name='StockCo')
        self.user = User.objects.create_user(
            username='stock_admin', email='sa@x.com', password='pw',
            is_staff=True, is_superuser=True,
        )
        # Active connection that we'll mock provider behavior for
        self.conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage',
            name='Ingram-test', is_active=True,
        )
        # Disabled connection — should be skipped by the view
        DistributorConnection.objects.create(
            organization=self.org, provider_type='pax8',
            name='Pax8-disabled', is_active=False,
        )
        self.client = Client()
        self.client.force_login(self.user)
        s = self.client.session
        s['2fa_prompted'] = True
        s['current_organization_id'] = self.org.id
        s.save()

    def test_no_query_renders_empty_form(self):
        r = self.client.get('/integrations/distributors/stock-check/')
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.context['has_query'], False)
        self.assertEqual(r.context['results'], [])

    def test_query_calls_only_active_providers(self):
        from unittest import mock

        def fake_get_provider(conn):
            mp = mock.MagicMock()
            mp.check_stock.return_value = {'sku': 'X', 'total_qty': 42}
            mp.get_pricing.return_value = {'sku': 'X', 'unit_price': 9.99,
                                            'currency': 'USD', 'available_qty': 42}
            return mp

        with mock.patch('integrations.providers.distributors.get_distributor_provider',
                         side_effect=fake_get_provider):
            r = self.client.get('/integrations/distributors/stock-check/?sku=X')
        self.assertEqual(r.status_code, 200)
        self.assertTrue(r.context['has_query'])
        # Only the active connection should be queried.
        self.assertEqual(len(r.context['results']), 1)
        row = r.context['results'][0]
        self.assertEqual(row['connection'].name, 'Ingram-test')
        self.assertTrue(row['ok'])
        self.assertEqual(row['qty'], 42)
        self.assertEqual(row['unit_price'], 9.99)

    def test_provider_error_captured(self):
        from unittest import mock

        def fake_get_provider(conn):
            mp = mock.MagicMock()
            mp.check_stock.return_value = {'error': 'unauthorized'}
            return mp

        with mock.patch('integrations.providers.distributors.get_distributor_provider',
                         side_effect=fake_get_provider):
            r = self.client.get('/integrations/distributors/stock-check/?sku=BAD')
        row = r.context['results'][0]
        self.assertFalse(row['ok'])
        self.assertEqual(row['error'], 'unauthorized')
        self.assertIsNone(row['qty'])

    def test_unknown_provider_handled(self):
        from unittest import mock
        with mock.patch('integrations.providers.distributors.get_distributor_provider',
                         return_value=None):
            r = self.client.get('/integrations/distributors/stock-check/?sku=Z')
        row = r.context['results'][0]
        self.assertFalse(row['ok'])
        self.assertIn('no provider', row['error'])


class GLAccountMappingTests(TestCase):
    """Phase 27 v6 (v3.17.278): per-line GL account mapping is propagated
    to QBO `ItemRef.value` and Xero `AccountCode` on push."""

    def setUp(self):
        from django.contrib.auth import get_user_model
        from psa.models import Invoice, InvoiceLineItem
        from datetime import date
        from decimal import Decimal as _D
        User = get_user_model()
        self.org = Organization.objects.create(name='GLOrg')
        # Need a separate "client" org for invoice (different role)
        self.client_org = Organization.objects.create(name='GLClient')
        self.invoice = Invoice.objects.create(
            organization=self.org, client_org=self.client_org,
            title='GL Test', invoice_date=date.today(),
            tax_rate=_D('0'),
        )
        InvoiceLineItem.objects.create(
            invoice=self.invoice, description='Mapped line',
            quantity=2, unit_price=_D('50'),
            gl_account_code='4100',  # consulting revenue
        )
        InvoiceLineItem.objects.create(
            invoice=self.invoice, description='Default line',
            quantity=1, unit_price=_D('25'),
            # gl_account_code blank → uses provider default
        )

    def test_qbo_payload_includes_itemref_when_set(self):
        """Without a real QBO sandbox, mock the HTTP call and inspect the
        body our adapter built."""
        from unittest import mock
        from .models import AccountingConnection
        from .providers.accounting.quickbooks_online import QuickBooksOnlineProvider
        conn = AccountingConnection.objects.create(
            organization=self.org, provider_type='quickbooks_online',
            name='qbo-gl-test',
        )
        provider = QuickBooksOnlineProvider(conn)
        captured = {}

        def fake_api(method, path, **kwargs):
            captured['method'] = method
            captured['path'] = path
            captured['body'] = kwargs.get('json')
            resp = mock.MagicMock()
            resp.status_code = 200
            resp.json.return_value = {'Invoice': {'Id': 'qbo-77'}}
            return resp

        with mock.patch.object(provider, '_ensure_customer',
                                return_value='cust-1'), \
             mock.patch.object(provider, '_api', side_effect=fake_api):
            result = provider.push_invoice(self.invoice)

        self.assertTrue(result['success'])
        body = captured['body']
        lines = body['Line']
        self.assertEqual(len(lines), 2)
        # Mapped line includes ItemRef
        line_with_ref = next((l for l in lines
                              if l['Description'] == 'Mapped line'), None)
        self.assertIsNotNone(line_with_ref)
        self.assertEqual(line_with_ref['SalesItemLineDetail']['ItemRef'],
                          {'value': '4100'})
        # Unmapped line does NOT include ItemRef
        line_default = next((l for l in lines
                             if l['Description'] == 'Default line'), None)
        self.assertIsNotNone(line_default)
        self.assertNotIn('ItemRef', line_default['SalesItemLineDetail'])

    def test_xero_payload_includes_accountcode_when_set(self):
        from unittest import mock
        from .models import AccountingConnection
        from .providers.accounting.xero import XeroProvider
        conn = AccountingConnection.objects.create(
            organization=self.org, provider_type='xero',
            name='xero-gl-test',
        )
        provider = XeroProvider(conn)
        captured = {}

        def fake_api(method, path, **kwargs):
            captured['body'] = kwargs.get('json')
            resp = mock.MagicMock()
            resp.status_code = 200
            resp.json.return_value = {'Invoices': [{'InvoiceID': 'xero-77'}]}
            return resp

        with mock.patch.object(provider, '_ensure_contact',
                                return_value='contact-1'), \
             mock.patch.object(provider, '_api', side_effect=fake_api):
            result = provider.push_invoice(self.invoice)

        self.assertTrue(result['success'])
        lines = captured['body']['Invoices'][0]['LineItems']
        mapped = next((l for l in lines
                       if l['Description'] == 'Mapped line'), None)
        default = next((l for l in lines
                        if l['Description'] == 'Default line'), None)
        self.assertEqual(mapped['AccountCode'], '4100')
        self.assertNotIn('AccountCode', default)
