# Generated by Django 6.0.1 on 2026-01-10 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorite_securenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Client St0r', max_length=255)),
                ('site_url', models.URLField(blank=True, help_text='Base URL for email links', max_length=500)),
                ('default_timezone', models.CharField(default='UTC', help_text='Default timezone for new users', max_length=50)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480, help_text='Session timeout in minutes (default: 8 hours)')),
                ('require_2fa', models.BooleanField(default=True, help_text='Require 2FA for all users')),
                ('password_min_length', models.PositiveIntegerField(default=12, help_text='Minimum password length')),
                ('password_require_special', models.BooleanField(default=True, help_text='Require special characters in passwords')),
                ('failed_login_attempts', models.PositiveIntegerField(default=5, help_text='Max failed login attempts before lockout')),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=30, help_text='Account lockout duration')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='Enable email notifications')),
                ('smtp_host', models.CharField(blank=True, help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='SMTP server port')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP username', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP password (encrypted)', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS for SMTP')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL for SMTP')),
                ('smtp_from_email', models.EmailField(blank=True, help_text='From email address', max_length=254)),
                ('smtp_from_name', models.CharField(default='Client St0r', help_text='From name', max_length=255)),
                ('notify_on_user_created', models.BooleanField(default=True, help_text='Notify admins when users are created')),
                ('notify_on_ssl_expiry', models.BooleanField(default=True, help_text='Send SSL expiration warnings')),
                ('notify_on_domain_expiry', models.BooleanField(default=True, help_text='Send domain expiration warnings')),
                ('ssl_expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Days before SSL expiry to warn')),
                ('domain_expiry_warning_days', models.PositiveIntegerField(default=60, help_text='Days before domain expiry to warn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
