# Generated by Django 6.0.1 on 2026-01-17 02:52

from django.db import migrations
import subprocess
import sys
import os
import logging

logger = logging.getLogger(__name__)


def apply_gunicorn_fix(apps, schema_editor):
    """
    Automatically apply the Gunicorn environment fix.

    This migration runs the fix_gunicorn_env.sh script to configure
    Gunicorn to load the .env file, fixing encryption errors with
    demo data import and password operations.
    """
    # Skip in test runs and on hosts without the production systemd unit.
    # The fix script targets `/etc/systemd/system/clientst0r-gunicorn.service`
    # and exits non-zero when that file isn't present, which logs noisy
    # "exited with code 1" banners on every test DB setup, in fresh dev
    # installs, in CI, and in containers without systemd. Skipping silently
    # keeps the migration a no-op where there's nothing to fix.
    if 'test' in sys.argv:
        return

    service_file = '/etc/systemd/system/clientst0r-gunicorn.service'
    if not os.path.exists(service_file):
        return

    fix_script_path = '/home/administrator/scripts/fix_gunicorn_env.sh'

    # Check if script exists
    if not os.path.exists(fix_script_path):
        logger.warning(f"Fix script not found at {fix_script_path}. Skipping auto-fix.")
        print(f"⚠️  Fix script not found at {fix_script_path}")
        print("   Please run ./scripts/fix_gunicorn_env.sh manually after update.")
        return

    # Check if script is executable
    if not os.access(fix_script_path, os.X_OK):
        logger.warning(f"Fix script is not executable. Making it executable...")
        try:
            os.chmod(fix_script_path, 0o755)
        except Exception as e:
            logger.error(f"Failed to make script executable: {e}")
            print(f"⚠️  Could not make script executable. Please run manually:")
            print(f"   chmod +x {fix_script_path}")
            print(f"   {fix_script_path}")
            return

    # Run the fix script
    try:
        logger.info("Running Gunicorn environment fix script...")
        print("\n" + "="*60)
        print("🔧 Applying Gunicorn Environment Fix (v2.24.116)")
        print("="*60)

        result = subprocess.run(
            [fix_script_path],
            capture_output=True,
            text=True,
            timeout=30
        )

        # Print the output
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)

        if result.returncode == 0:
            logger.info("✓ Gunicorn fix applied successfully")
            print("\n✅ Gunicorn environment fix applied successfully!")
            print("   Demo data import and encryption operations should now work.\n")
        else:
            logger.error(f"Fix script exited with code {result.returncode}")
            print(f"\n⚠️  Fix script exited with code {result.returncode}")
            print("   Please run manually if issues persist:")
            print(f"   {fix_script_path}\n")

    except subprocess.TimeoutExpired:
        logger.error("Fix script timed out after 30 seconds")
        print("\n⚠️  Fix script timed out. Please run manually:")
        print(f"   {fix_script_path}\n")
    except Exception as e:
        logger.error(f"Error running fix script: {e}")
        print(f"\n⚠️  Error running fix script: {e}")
        print("   Please run manually:")
        print(f"   {fix_script_path}\n")


def reverse_func(apps, schema_editor):
    """No reverse operation needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_github_pat'),
    ]

    operations = [
        migrations.RunPython(apply_gunicorn_fix, reverse_func),
    ]
