# Generated by Django 6.0.1 on 2026-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_firewall_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='custom_company_name',
            field=models.CharField(blank=True, help_text='Custom company name (replaces Client St0r branding)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='custom_logo',
            field=models.ImageField(blank=True, help_text='Custom logo (recommended: 200x40px PNG with transparent background)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='custom_logo_height',
            field=models.PositiveIntegerField(default=30, help_text='Logo height in pixels (default: 30px)'),
        ),
    ]
