# Generated by Django 6.0.1 on 2026-02-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_snyk_product_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='reports_enabled',
            field=models.BooleanField(default=True, help_text='Enable Reports & Analytics feature'),
        ),
    ]
