# Generated by Django 6.0.1 on 2026-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_systemsetting_reports_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Client service type (e.g., Fully Managed, Break/Fix, etc.)', max_length=100),
        ),
    ]
