# Generated by Django 6.0.2 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_webhooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPackageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('package_manager', models.CharField(help_text='Package manager used (apt, yum, dnf, pacman)', max_length=50)),
                ('total_packages', models.IntegerField(default=0)),
                ('upgradeable_packages', models.IntegerField(default=0)),
                ('security_updates', models.IntegerField(default=0)),
                ('scan_data', models.JSONField(default=dict, help_text='Full scan results including package details')),
            ],
            options={
                'db_table': 'system_package_scans',
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['-scan_date'], name='system_pack_scan_da_4cbddf_idx')],
            },
        ),
    ]
