# Generated by Django 5.0 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_vehicles_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='inventory_enabled',
            field=models.BooleanField(default=True, help_text='Enable Inventory management'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='scheduling_enabled',
            field=models.BooleanField(default=True, help_text='Enable Scheduling and Task Management'),
        ),
    ]
