# Generated by Django 6.0.4 on 2026-04-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_psa_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pythonpackagescan',
            new_name='python_pack_scan_da_05e073_idx',
            old_name='python_pack_scan_da_idx',
        ),
        migrations.RenameIndex(
            model_name='systemwarningnotification',
            new_name='system_warn_notifie_a08051_idx',
            old_name='system_warn_notifie_idx',
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('asset_age_check', 'Asset Age Warning Check'), ('cleanup_stuck_scans', 'Cleanup Stuck Security Scans'), ('domain_expiry_check', 'Domain Expiry Check'), ('equipment_catalog_update', 'Equipment Catalog Update'), ('firmware_check', 'Firmware Update Check'), ('password_breach_scan', 'Password Breach Scanning'), ('python_dep_scan', 'Python Dependency Vulnerability Scan'), ('system_warnings_digest', 'System Warnings Digest Email'), ('vault_password_expiry', 'Vault Password Expiry Notifications'), ('psa_sync', 'PSA Synchronization'), ('rmm_sync', 'RMM Synchronization'), ('scheduling_alerts', 'Scheduled Task Alerts'), ('security_scan', 'Automated Security Scan'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('update_check', 'System Update Check'), ('warranty_check', 'Warranty Expiry Check'), ('website_monitoring', 'Website Monitoring Checks')], max_length=50, unique=True),
        ),
    ]
