# Generated by Django 6.0.4 on 2026-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_psa_global_surface_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_anthropic_api_key',
            field=models.CharField(blank=True, help_text='Anthropic API key (encrypted at rest). Leave blank to fall back to the ANTHROPIC_API_KEY env var.', max_length=512),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_blocked_subject_keywords',
            field=models.TextField(blank=True, help_text='Newline-separated; suggestions are skipped when the ticket subject matches any of these (case-insensitive substring match).'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_daily_token_limit',
            field=models.PositiveIntegerField(default=200000, help_text='Per-organization daily token budget. AI generation stops for the day at this limit.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI Suggested Replies + Suggested Actions on PSA tickets (off by default)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_min_confidence',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Suggestions below this confidence (0–1) are shown collapsed and cannot be one-click approved.', max_digits=4),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_model_actions',
            field=models.CharField(default='claude-haiku-4-5-20251001', help_text='Model for structured action suggestions (Haiku is cheaper and fast)', max_length=80),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_model_replies',
            field=models.CharField(default='claude-sonnet-4-6', help_text='Model for client-facing reply drafts (Sonnet recommended)', max_length=80),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_provider',
            field=models.CharField(default='anthropic', help_text='AI provider — currently only "anthropic" is supported', max_length=30),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_suggestion_ttl_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Suggestions older than this auto-expire (cannot be applied).'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_voice',
            field=models.TextField(blank=True, default='Professional, concise, confident.', help_text='Free-form sentence injected into the system prompt — sets the MSP voice/tone.'),
        ),
    ]
