# Generated by Django 6.0.4 on 2026-04-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_psa_ai_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='psa_ai_anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='psa_ai_model_actions',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='psa_ai_model_replies',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='psa_ai_provider',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_max_output_tokens',
            field=models.PositiveIntegerField(default=2000, help_text='Hard cap on a single AI response — prevents runaway costs / over-long replies.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_per_user_daily_limit',
            field=models.PositiveIntegerField(default=50000, help_text='Per-user daily token cap (anti-abuse — one user cannot drain the org pool).'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_ai_per_user_rate_per_min',
            field=models.PositiveIntegerField(default=10, help_text='Max AI generations per user per minute (anti-abuse).'),
        ),
    ]
