# Generated by Django 6.0.4 on 2026-04-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='psa_default_currency',
            field=models.CharField(default='USD', help_text='Default currency for new invoices (ISO 4217 code).', max_length=8),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_default_tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Default tax rate for new quotes / invoices (e.g. 0.0875 for 8.75%). Each quote/invoice can still override.', max_digits=5),
        ),
    ]
