# Generated by Django 6.0.4 on 2026-04-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsetting_psa_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='crm_enabled',
            field=models.BooleanField(default=False, help_text='Enable CRM / sales pipeline (leads, opportunities, campaigns, commissions). Off by default.'),
        ),
    ]
