# Generated by Django 6.0.4 on 2026-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_systemsetting_psa_csat_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='portal_primary_color',
            field=models.CharField(blank=True, help_text="v3.17.233: hex color (e.g. #0d6efd) used as the primary accent on this org's customer portal pages. Empty = fall back to the system default.", max_length=20),
        ),
    ]
