# Generated by Django 6.0.4 on 2026-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_systemsetting_psa_portal_announcements_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='invoice_approval_overage_pct',
            field=models.PositiveIntegerField(default=0, help_text='Auto-flag invoices when their source contract is at >= this consumed-percent. 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='invoice_approval_threshold_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-flag invoices for manager approval when total >= this dollar amount. 0 = disabled.', max_digits=12),
        ),
    ]
