# Generated by Django 6.0.4 on 2026-05-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_systemsetting_invoice_approval_overage_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='quote_approval_threshold_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Auto-create a PSAApproval chain when a Quote's total >= this dollar amount. 0 = disabled.", max_digits=12),
        ),
    ]
