# Generated by Django 6.0.4 on 2026-05-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_systemsetting_quote_approval_threshold_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, help_text='Region / area tag — drives the multi-location report grouping. Free-text, normalized to lowercase for grouping.', max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='sla_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-priority SLA override map: {"P1": {"response_minutes": 15, "resolution_minutes": 240}}. Empty = inherit from contract / queue defaults.'),
        ),
    ]
