# Generated by Django 6.0.4 on 2026-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_organization_region_organization_sla_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='late_fee_min_days_overdue',
            field=models.PositiveIntegerField(default=15, help_text='Days past due_date before a late fee is applied.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='late_fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee percent of overdue balance (e.g. 1.5 = 1.5%%). 0 = disabled.', max_digits=5),
        ),
    ]
