# Generated by Django 6.0.4 on 2026-05-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_betatesterrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='betatesterrequest',
            new_name='core_beta_t_status_67f992_idx',
            old_name='core_beta_t_status_idx',
        ),
        migrations.RenameIndex(
            model_name='betatesterrequest',
            new_name='core_beta_t_google__86c0c8_idx',
            old_name='core_beta_t_email_idx',
        ),
        migrations.AddField(
            model_name='betatesterrequest',
            name='source_install',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
