# Generated by Django 6.0.2 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('owner', 'Owner'), ('readonly', 'Read-Only')], default='readonly', max_length=20),
        ),
    ]
