# Generated by Django 6.0.4 on 2026-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_system_package_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('single', 'Single organization'), ('descendants', 'Organization + sub-locations'), ('all', 'All accessible organizations')], default='single', help_text='Which organizations this key can address', max_length=20),
        ),
    ]
