# Generated by Django 6.0.4 on 2026-04-28 00:25

import django.db.models.deletion
import psa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0014_asset_health_features'),
        ('core', '0044_rename_python_pack_scan_da_idx_python_pack_scan_da_05e073_idx_and_more'),
        ('docs', '0012_add_system_package_scan'),
        ('scheduling', '0002_add_psa_ticket_and_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'psa_queues',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code, e.g. 'P1'", max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('response_target_minutes', models.PositiveIntegerField(default=240, help_text='Default response SLA target')),
                ('resolution_target_minutes', models.PositiveIntegerField(default=4320, help_text='Default resolution SLA target')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket priorities',
                'db_table': 'psa_ticket_priorities',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_terminal', models.BooleanField(default=False, help_text='True for resolved/closed/cancelled-style states')),
                ('pauses_sla', models.BooleanField(default=False, help_text='True if SLA clock pauses while in this state')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket statuses',
                'db_table': 'psa_ticket_statuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'psa_ticket_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPSASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable PSA for this client')),
                ('portal_enabled', models.BooleanField(default=False, help_text='Allow this client to use the customer portal')),
                ('anonymous_ticket_form_enabled', models.BooleanField(default=False, help_text='Allow public/anonymous ticket submission')),
                ('email_to_ticket_enabled', models.BooleanField(default=False, help_text='Convert inbound emails to tickets')),
                ('sms_notifications_enabled', models.BooleanField(default=False, help_text='Send SMS to staff for this client (no secrets)')),
                ('desktop_alerts_enabled', models.BooleanField(default=False, help_text='Send desktop/browser alerts to staff for this client')),
                ('external_alert_ingest_enabled', models.BooleanField(default=False, help_text='Accept alerts from external monitoring/RMM for this client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psa_settings', to='core.organization')),
            ],
            options={
                'verbose_name': 'Client PSA Settings',
                'verbose_name_plural': 'Client PSA Settings',
                'db_table': 'psa_client_settings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('requester_name', models.CharField(blank=True, help_text='Free-text requester (e.g. anonymous portal)', max_length=200)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('assigned_team', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('portal', 'Client Portal'), ('email', 'Email'), ('sms', 'SMS'), ('rmm', 'RMM'), ('api', 'API'), ('monitoring', 'Monitoring'), ('anonymous', 'Anonymous Form'), ('calendar', 'Calendar')], default='manual', max_length=20)),
                ('visibility', models.CharField(choices=[('staff', 'Staff Only'), ('client', 'Visible to Client')], default='staff', max_length=20)),
                ('client_can_view', models.BooleanField(default=False)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of free-form string tags')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_tech_response_at', models.DateTimeField(blank=True, null=True)),
                ('sla_paused_until', models.DateTimeField(blank=True, null=True)),
                ('sla_breached_response', models.BooleanField(default=False)),
                ('sla_breached_resolution', models.BooleanField(default=False)),
                ('waiting_on_vendor', models.BooleanField(default=False)),
                ('vendor_ticket_number', models.CharField(blank=True, max_length=100)),
                ('vendor_contact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, help_text='Customer-side contact who requested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_psa_tickets', to='assets.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='psa.ticket')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_psa_tickets', to='core.organization')),
                ('parent_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tickets', to='psa.ticket')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='psa.queue')),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_psa_tickets', to='assets.asset')),
                ('related_calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_psa_tickets', to='scheduling.scheduledtask')),
                ('related_documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_psa_doc_tickets', to='docs.document')),
                ('related_kb_article', models.ForeignKey(blank=True, help_text='KB article (docs.Document with is_global=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_psa_kb_tickets', to='docs.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_tickets_updated', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='psa.ticketpriority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='psa.ticketstatus')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='psa.tickettype')),
            ],
            options={
                'db_table': 'psa_native_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal-only — never shown to the client')),
                ('is_system', models.BooleanField(default=False, help_text='Auto-generated event (status change, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_ticket_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=psa.models.ticket_attachment_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='psa.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_attachments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, help_text='Optional — link this attachment to a specific comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='psa.ticketcomment')),
            ],
            options={
                'db_table': 'psa_ticket_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'created_at'], name='psa_ticket__ticket__65ff9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'is_internal'], name='psa_ticket__ticket__da924c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket', '-created_at'], name='psa_ticket__ticket__f22424_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', '-created_at'], name='psa_native__organiz_25eaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='psa_native__status__19e3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', '-created_at'], name='psa_native__assigne_42c67a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', '-created_at'], name='psa_native__priorit_dee79f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='psa_native__ticket__7e5016_idx'),
        ),
    ]
