# Generated by Django 6.0.4 on 2026-04-28 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0004_watchers_and_canned_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown in the catalog grid')),
                ('default_subject', models.CharField(blank=True, max_length=300)),
                ('default_body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class, e.g. "fas fa-user-plus"', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='psa.ticketpriority')),
                ('default_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='psa.queue')),
                ('default_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='psa.tickettype')),
            ],
            options={
                'db_table': 'psa_service_catalog_items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Computed on save when ended_at is set')),
                ('is_billable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='psa.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_ticket_time_entries',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['ticket', '-started_at'], name='psa_ticket__ticket__55a3c5_idx'), models.Index(fields=['user', '-started_at'], name='psa_ticket__user_id_b98403_idx'), models.Index(fields=['ticket', 'is_billable'], name='psa_ticket__ticket__c2a246_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('ticket', 'user'), name='psa_one_running_timer_per_user_per_ticket')],
            },
        ),
    ]
