# Generated by Django 6.0.4 on 2026-04-28 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('docs', '0012_add_system_package_scan'),
        ('psa', '0006_catalog_fields_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(blank=True, help_text='Client organization the project is for (null = internal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_client_projects', to='core.organization')),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the project', on_delete=django.db.models.deletion.CASCADE, related_name='psa_projects', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_psa_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Group this ticket under a PSA project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='psa.project'),
        ),
        migrations.CreateModel(
            name='PSAApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('time', 'Time entry'), ('expense', 'Expense'), ('quote', 'Quote / estimate'), ('order', 'Distributor order'), ('action', 'AI action'), ('change', 'Change / scope'), ('other', 'Other')], max_length=20)),
                ('object_type', models.CharField(help_text='app_label.ModelName of the thing being approved', max_length=80)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_approvals', to='core.organization')),
                ('related_ticket', models.ForeignKey(blank=True, help_text='If the approval is tied to a specific ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='psa.ticket')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_approvals',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTicketSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this schedule', max_length=200)),
                ('template_subject', models.CharField(max_length=300)),
                ('template_body', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Run every N units (e.g. interval=2, frequency=weekly = every 2 weeks)')),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to=settings.AUTH_USER_MODEL)),
                ('client_org', models.ForeignKey(blank=True, help_text='Client the recurring ticket targets (null = internal/MSP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_client_recurring_schedules', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_recurring_schedules', to='core.organization')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='psa.ticketpriority')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='psa.queue')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='psa.tickettype')),
            ],
            options={
                'db_table': 'psa_recurring_schedules',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='recurring_schedule',
            field=models.ForeignKey(blank=True, help_text='Set when the ticket was created by a recurring schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tickets', to='psa.recurringticketschedule'),
        ),
        migrations.CreateModel(
            name='TicketKBLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Optional context on why this article was linked', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_ticket_links', to='docs.document')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_links_created', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_links', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_ticket_kb_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='psa_project_organiz_5dc66a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_org', 'status'], name='psa_project_client__a66c20_idx'),
        ),
        migrations.AddIndex(
            model_name='psaapproval',
            index=models.Index(fields=['organization', 'status', '-requested_at'], name='psa_approva_organiz_9a0bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='psaapproval',
            index=models.Index(fields=['object_type', 'object_id'], name='psa_approva_object__9c346e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringticketschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='psa_recurri_is_acti_46fdbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketkblink',
            unique_together={('ticket', 'article')},
        ),
    ]
