# Generated by Django 6.0.4 on 2026-04-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0007_project_ticket_project_psaapproval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('portal', 'Client Portal'), ('email', 'Email'), ('sms', 'SMS'), ('rmm', 'RMM'), ('api', 'API'), ('monitoring', 'Monitoring'), ('anonymous', 'Anonymous Form'), ('calendar', 'Calendar'), ('recurring', 'Recurring Schedule')], default='manual', max_length=20),
        ),
    ]
