# Generated by Django 6.0.4 on 2026-04-28 15:42

import django.db.models.deletion
import psa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('psa', '0010_ticketcomment_author_email_ticketcomment_author_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='e.g. 0.0875 for 8.75%', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_client_quotes', to='core.organization')),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='psa.project')),
                ('converted_ticket', models.ForeignKey(blank=True, help_text='Set when the quote was converted to a ticket on acceptance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='psa.ticket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_psa_quotes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_quotes', to='core.organization')),
            ],
            options={
                'db_table': 'psa_quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_taxable', models.BooleanField(default=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='psa.quote')),
            ],
            options={
                'db_table': 'psa_quote_line_items',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mileage', 'Mileage / Travel'), ('parts', 'Parts'), ('software', 'Software / License'), ('subcontractor', 'Subcontractor'), ('shipping', 'Shipping'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('incurred_on', models.DateField()),
                ('is_billable', models.BooleanField(default=True)),
                ('is_reimbursable', models.BooleanField(default=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=psa.models.expense_receipt_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='psa.psaapproval')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='psa.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_ticket_expenses',
                'ordering': ['-incurred_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='psa_quotes_organiz_be0002_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client_org', 'status'], name='psa_quotes_client__53e9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['ticket', '-incurred_on'], name='psa_ticket__ticket__449505_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexpense',
            index=models.Index(fields=['user', '-incurred_on'], name='psa_ticket__user_id_3b32ea_idx'),
        ),
    ]
