# Generated by Django 6.0.4 on 2026-04-28 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('psa', '0012_projecttask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('ticket_created', 'Ticket created'), ('ticket_updated', 'Ticket updated'), ('status_changed', 'Status changed'), ('comment_added', 'Comment added')], max_length=30)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower runs first when multiple rules match')),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('fire_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_psa_workflow_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='MSP tenant; rules apply only to tickets within this tenant', on_delete=django.db.models.deletion.CASCADE, related_name='psa_workflow_rules', to='core.organization')),
            ],
            options={
                'db_table': 'psa_workflow_rules',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['organization', 'trigger', 'is_active'], name='psa_workflo_organiz_63e380_idx')],
            },
        ),
    ]
