# Generated by Django 6.0.4 on 2026-04-29 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsetting_psa_default_currency_and_more'),
        ('psa', '0016_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrule',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply this rule to tickets from EVERY client. Set to a specific client organization to scope it to that client only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psa_workflow_rules', to='core.organization'),
        ),
    ]
