# Generated by Django 6.0.4 on 2026-04-30 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0021_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='source_quote',
            field=models.ForeignKey(blank=True, help_text='Phase 4.4: set when this PO was auto-created from an accepted quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='psa.quote'),
        ),
    ]
