# Generated by Django 6.0.4 on 2026-04-30 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsetting_crm_enabled'),
        ('psa', '0022_purchaseorder_source_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(choices=[('low', 'Low - routine, well-tested'), ('medium', 'Medium - significant scope'), ('high', 'High - service-impacting potential'), ('emergency', 'Emergency - out-of-band, post-implement review')], default='medium', max_length=20)),
                ('implementation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_cab', 'Pending CAB Approval'), ('approved', 'Approved - Ready to Implement'), ('rejected', 'Rejected by CAB'), ('implementing', 'Implementing'), ('verified', 'Verified - Successful'), ('failed', 'Failed - Rolled Back'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('implementation_plan', models.TextField(blank=True, help_text='Step-by-step plan. Required before submitting to CAB.')),
                ('rollback_plan', models.TextField(blank=True, help_text='If the change fails, how do we revert? Required for high/emergency risk.')),
                ('impact_assessment', models.TextField(blank=True)),
                ('backout_window_minutes', models.PositiveIntegerField(blank=True, help_text='Maximum minutes the change can run before triggering auto-rollback considerations.', null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('outcome_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_change_requests', to='core.organization')),
                ('required_approvers', models.ManyToManyField(blank=True, help_text='Each must approve before the change moves to Implementing. Empty = single approver via the existing PSAApproval flow.', related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_request', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CABVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('abstained', 'Abstained')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab_votes', to='psa.changerequest')),
            ],
            options={
                'db_table': 'psa_cab_votes',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['organization', 'implementation_status', '-created_at'], name='psa_change__organiz_5d6a08_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['risk', 'implementation_status'], name='psa_change__risk_efce84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cabvote',
            unique_together={('change_request', 'user')},
        ),
    ]
