# Generated by Django 6.0.4 on 2026-04-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsetting_crm_enabled'),
        ('psa', '0023_changerequest_cabvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('known_error', 'Known Error - Workaround Available'), ('resolved', 'Resolved - Permanent Fix Deployed'), ('closed', 'Closed'), ('duplicate', 'Duplicate of Another Problem')], default='investigating', max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('symptoms', models.TextField(blank=True, help_text='What the user / monitoring observed. The problem manifestation.')),
                ('root_cause', models.TextField(blank=True, help_text='Underlying cause. Required to flip status to known_error or resolved.')),
                ('workaround', models.TextField(blank=True, help_text='Temporary mitigation. Required when status=known_error.')),
                ('permanent_fix', models.TextField(blank=True, help_text='Permanent resolution. Required when status=resolved.')),
                ('five_whys', models.JSONField(blank=True, default=list, help_text='Optional structured 5-whys list - each entry is a string.')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_problems_owned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_problems_created', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='If this problem turns out to be a duplicate, link to the canonical one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='psa.problem')),
                ('fix_change_request', models.ForeignKey(blank=True, help_text='Optional link to the Change that deployed the permanent fix.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_fixed', to='psa.changerequest')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_problems', to='core.organization')),
                ('related_tickets', models.ManyToManyField(blank=True, help_text='Incidents that share this underlying root cause.', related_name='problems', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_breakthrough', models.BooleanField(default=False, help_text='Mark when this note records a key analytical finding.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='psa.problem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_problem_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='psa_problem_organiz_416203_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['priority', 'status'], name='psa_problem_priorit_ebf8bc_idx'),
        ),
    ]
