# Generated by Django 6.0.4 on 2026-04-30 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsetting_crm_enabled'),
        ('psa', '0024_problem_problemnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalogitem',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='last_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='When true, edits require approval via ServiceCatalogChange before publishing.'),
        ),
        migrations.CreateModel(
            name='ReleaseWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('frozen', 'Frozen — In Progress'), ('completed', 'Completed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False, help_text='When true, no new changes can be added; existing changes locked.')),
                ('rollback_plan', models.TextField(blank=True, help_text='If the release fails, what do we revert? Required before status flips to frozen / completed.')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changes', models.ManyToManyField(blank=True, related_name='release_windows', to='psa.changerequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_release_windows', to='core.organization')),
                ('release_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_release_windows_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_release_windows',
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['organization', 'status', '-scheduled_start'], name='psa_release_organiz_0b0bc0_idx'), models.Index(fields=['scheduled_start', 'scheduled_end'], name='psa_release_schedul_0721de_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_proposals', to='psa.servicecatalogitem')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_service_catalog_changes',
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['catalog_item', 'status'], name='psa_service_catalog_d31902_idx'), models.Index(fields=['proposed_by', 'status'], name='psa_service_propose_cf7139_idx')],
            },
        ),
    ]
