# Generated by Django 6.0.4 on 2026-05-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
        ('psa', '0027_email_message_threading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Free-text label shown in the rules list.', max_length=120)),
                ('sender_domain_glob', models.CharField(help_text='Match pattern. Examples: "acme.com" (exact domain), "*.acme.com" (any subdomain), "noreply@acme.com" (specific sender). Case-insensitive.', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100, help_text='Lower fires first; first match wins.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'psa_email_routing_rules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='quarantine_reason',
            field=models.CharField(blank=True, help_text='One-line reason; cross-check raw headers for detail.', max_length=200),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='was_quarantined',
            field=models.BooleanField(db_index=True, default=False, help_text='Phase 10.3: True when the message was filtered out of the normal ingestion path (auto-responder, DMARC fail, spam).'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='Phase 10.3: NULL only for quarantined inbound mail that was rejected before any ticket was created or matched. Normal inbound + outbound rows always have a ticket.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='psa.ticket'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['organization', 'was_quarantined', 'received_at'], name='psa_email_m_organiz_407cc7_idx'),
        ),
        migrations.AddField(
            model_name='emailroutingrule',
            name='organization',
            field=models.ForeignKey(help_text='MSP tenant that owns this rule.', on_delete=django.db.models.deletion.CASCADE, related_name='psa_email_routing_rules', to='core.organization'),
        ),
        migrations.AddField(
            model_name='emailroutingrule',
            name='priority_override',
            field=models.ForeignKey(blank=True, help_text='Optional priority override; falls back to the ingestion config default when blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_routing_rules', to='psa.ticketpriority'),
        ),
        migrations.AddField(
            model_name='emailroutingrule',
            name='queue_override',
            field=models.ForeignKey(blank=True, help_text='Optional queue override; falls back to the ingestion config default when blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_routing_rules', to='psa.queue'),
        ),
        migrations.AddField(
            model_name='emailroutingrule',
            name='target_client_org',
            field=models.ForeignKey(help_text='Client org to route matching alerts/tickets to.', on_delete=django.db.models.deletion.CASCADE, related_name='psa_routing_targeted_by', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='emailroutingrule',
            index=models.Index(fields=['organization', 'enabled', 'order'], name='psa_email_r_organiz_32b351_idx'),
        ),
    ]
