# Generated by Django 6.0.4 on 2026-05-02 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0030_ticketcsatsurvey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='psa.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_ticket_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_ticket_votes',
                'indexes': [models.Index(fields=['ticket'], name='psa_ticket__ticket__23420c_idx')],
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
