# Generated by Django 6.0.4 on 2026-05-02 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0034_psaapproval_is_client_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('submitter_notes', models.TextField(blank=True, help_text='Optional comment from the tech when submitting.')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_timesheet_decisions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_timesheet_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_timesheet_submissions',
                'ordering': ['-period_start', '-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='tickettimeentry',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Weekly batch this entry belongs to. Null = unsubmitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='psa.timesheetsubmission'),
        ),
        migrations.AddIndex(
            model_name='timesheetsubmission',
            index=models.Index(fields=['user', '-period_start'], name='psa_timeshe_user_id_0a95b0_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='psa_timeshe_status_1d89c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheetsubmission',
            unique_together={('user', 'period_start', 'period_end')},
        ),
    ]
