# Generated by Django 6.0.4 on 2026-05-04 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_systemsetting_invoice_approval_overage_pct_and_more'),
        ('psa', '0038_psaapproval_parent_approval_psaapproval_stage_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPurchaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Snapshot of the target vendor; line items are stored as a JSON list of {description, sku, quantity, unit_price}.', max_length=200)),
                ('line_items_snapshot', models.JSONField(blank=True, default=list, help_text='List of dicts: [{"description":"…","sku":"…","quantity":1,"unit_price":0,"distributor_provider":""}, …]')),
                ('recurrence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_run_at', models.DateField(help_text='Next date the cron should spawn a PR from this template.')),
                ('last_run_at', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(blank=True, help_text='Optional bill-to / drop-ship-to client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_purchase_templates_for_client', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the template.', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_purchase_templates', to='core.organization')),
            ],
            options={
                'db_table': 'psa_recurring_purchase_templates',
                'ordering': ['next_run_at', 'name'],
                'indexes': [models.Index(fields=['organization', 'enabled', 'next_run_at'], name='psa_recurri_organiz_ebf9eb_idx')],
            },
        ),
    ]
