# Generated by Django 6.0.4 on 2026-05-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0039_recurringpurchasetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount reported by the accounting provider on the most recent push. Compare to `tax_amount` (our local calculation) to detect drift.', max_digits=12, null=True),
        ),
    ]
