# Generated by Django 6.0.4 on 2026-05-05 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0040_invoice_provider_tax_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequestTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='psa.changerequest')),
            ],
            options={
                'db_table': 'psa_change_request_transitions',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['change_request', '-at'], name='psa_change__change__75a8fd_idx')],
            },
        ),
    ]
