# Generated by Django 6.0.4 on 2026-05-05 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0041_changerequesttransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='signed_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='signoff_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='requires_signoff',
            field=models.BooleanField(default=False, help_text='Block transitions into this status unless the ticket has been signed off (signed_off_at populated).'),
        ),
    ]
