# Generated by Django 6.0.4 on 2026-05-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0042_ticket_signed_off_at_ticket_signed_off_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='gl_account_code',
            field=models.CharField(blank=True, help_text='Provider-side GL account code (QBO Item ref or Xero AccountCode). Blank uses the connection default.', max_length=40),
        ),
    ]
