# Generated by Django 6.0.4 on 2026-05-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0044_invoice_target_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_deposit_batch',
            field=models.CharField(blank=True, db_index=True, help_text='Opaque tag grouping payments that share a single bank deposit. Used by the bank-reconciliation report.', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_reconciled_at',
            field=models.DateTimeField(blank=True, help_text='When the deposit batch was confirmed against the bank statement.', null=True),
        ),
    ]
