# Generated by Django 6.0.4 on 2026-05-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0046_workflowrule_else_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrule',
            name='fire_once_per_ticket',
            field=models.BooleanField(default=False, help_text="Fire at most once per (rule, ticket). Use for SLA-driven rules so the cron doesn't spam."),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='trigger',
            field=models.CharField(choices=[('ticket_created', 'Ticket created'), ('ticket_updated', 'Ticket updated'), ('status_changed', 'Status changed'), ('comment_added', 'Comment added'), ('sla_threshold_crossed', 'SLA threshold crossed')], max_length=30),
        ),
        migrations.CreateModel(
            name='WorkflowRuleFiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firings', to='psa.workflowrule')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_firings', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_workflow_rule_firings',
                'indexes': [models.Index(fields=['ticket', '-fired_at'], name='psa_workflo_ticket__b69a62_idx')],
                'unique_together': {('rule', 'ticket')},
            },
        ),
    ]
