# Generated by Django 6.0.4 on 2026-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0049_workflowsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billing_frequency',
            field=models.CharField(choices=[('none', 'No recurring billing'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', help_text='How often a draft Invoice is auto-generated for this contract. Set to "none" to disable recurring billing.', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_billed_at',
            field=models.DateField(blank=True, help_text='Date of the most recent recurring-invoice generation.', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_billing_date',
            field=models.DateField(blank=True, help_text='Next date the recurring-invoice cron should fire. Auto-advanced after each generation.', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='recurring_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-period billing amount. When 0, derived from `total_hours * hourly_rate` for retainer-style contracts.', max_digits=12),
        ),
    ]
