# Generated by Django 6.0.4 on 2026-05-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0050_contract_billing_frequency_contract_last_billed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('seat', 'Seat / user'), ('device', 'Device / endpoint'), ('gb', 'GB (storage / bandwidth)'), ('hour', 'Hour'), ('item', 'Generic item')], default='seat', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Accumulated since last billing. Reset after invoice generation.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_billed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='psa.contract')),
            ],
            options={
                'db_table': 'psa_contract_meters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['contract', 'is_active'], name='psa_contrac_contrac_ebf0b5_idx')],
            },
        ),
    ]
