# Generated by Django 6.0.4 on 2026-05-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0053_mileagelog_sitevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_ticket_checklist_items',
                'ordering': ['sort_order', 'pk'],
                'indexes': [models.Index(fields=['ticket', 'is_completed'], name='psa_ticket__ticket__45785e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_name', models.CharField(max_length=200)),
                ('signed_by_title', models.CharField(blank=True, max_length=200)),
                ('signature_data', models.TextField(help_text='Base64 data URI of the drawn signature (image/png)')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('captured_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('captured_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_signature', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_ticket_signatures',
                'indexes': [models.Index(fields=['ticket'], name='psa_ticket__ticket__0d5147_idx')],
            },
        ),
    ]
