# Generated by Django 6.0.4 on 2026-05-05 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0054_ticketchecklistitem_ticketsignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Browser-issued push endpoint URL.', max_length=600)),
                ('p256dh_key', models.CharField(help_text='Public key from the browser (base64).', max_length=200)),
                ('auth_secret', models.CharField(help_text='Auth secret from the browser (base64).', max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_web_push_subscriptions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='psa_web_pus_user_id_979b20_idx')],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
