# Generated by Django 6.0.4 on 2026-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0055_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='voice_meta',
            field=models.JSONField(blank=True, default=dict, help_text='When source=voice: {confidence, language, duration_s}'),
        ),
        migrations.AddField(
            model_name='tickettimeentry',
            name='end_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tickettimeentry',
            name='end_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='tickettimeentry',
            name='start_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tickettimeentry',
            name='start_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='source',
            field=models.CharField(default='manual', help_text='manual | email | portal | api | voice | workflow', max_length=20),
        ),
    ]
