# Generated by Django 6.0.1 on 2026-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_feature_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='lifespan_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Enable reminders for upcoming end-of-life'),
        ),
        migrations.AddField(
            model_name='asset',
            name='lifespan_reminder_months',
            field=models.PositiveIntegerField(default=6, help_text='Send reminder X months before end-of-life'),
        ),
        migrations.AddField(
            model_name='asset',
            name='lifespan_years',
            field=models.PositiveIntegerField(blank=True, help_text='Expected lifespan in years (e.g., 3-5 for servers, 5-7 for firewalls)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date asset was purchased or deployed', null=True),
        ),
    ]
