# Generated by Django 6.0.2 on 2026-04-11 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_ai_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private notes visible only to the author')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_notes', to='assets.contact')),
            ],
            options={
                'db_table': 'contact_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback note for this rating')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assets.contact')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
