# Generated by Django 6.0.4 on 2026-05-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_vendor_account_number_vendor_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_shared_with_descendants',
            field=models.BooleanField(default=False, help_text='Make this asset visible to descendants of its organization via the parent/child hierarchy. Use for shared infrastructure consumed across multiple sites.'),
        ),
    ]
