# Generated by Django 6.0.4 on 2026-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_asset_is_shared_with_descendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_warranty_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
