# Generated by Django 6.0.4 on 2026-05-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_asset_last_warranty_alert_sent_at'),
        ('core', '0055_systemsetting_invoice_approval_overage_pct_and_more'),
        ('psa', '0036_psaapproval_escalated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMAReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rma_number', models.CharField(blank=True, help_text='Vendor-issued RMA / case number.', max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, help_text='Short reason: DOA, defective, wrong-spec, etc.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sent', 'Sent to vendor'), ('received_by_vendor', 'Received by vendor'), ('replaced', 'Replacement received'), ('refunded', 'Refunded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_serial', models.CharField(blank=True, help_text='Serial of the replacement unit (when status=replaced).', max_length=120)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Refund amount in PO currency (when status=refunded).', max_digits=12, null=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Optional — the physical unit being returned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_returns', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_returns', to='core.organization')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Optional — the PO the bad unit was sourced from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_returns', to='psa.purchaseorder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_returns', to='assets.vendor')),
            ],
            options={
                'db_table': 'rma_returns',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['organization', '-opened_at'], name='rma_returns_organiz_ad0e3d_idx'), models.Index(fields=['status'], name='rma_returns_status_c999f8_idx'), models.Index(fields=['vendor'], name='rma_returns_vendor__9e1bcd_idx')],
            },
        ),
    ]
