# Generated by Django 6.0.4 on 2026-05-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_assetbaseline'),
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('pattern', models.CharField(help_text='Case-insensitive substring matched against software name (e.g. "TeamViewer" matches "TeamViewer 15.x").', max_length=200)),
                ('action', models.CharField(choices=[('deny', 'Deny — flag installs as violations'), ('require', 'Require — flag missing as violations')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, help_text='None = MSP-wide policy applied to every client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_policies', to='core.organization')),
            ],
            options={
                'db_table': 'software_policies',
                'ordering': ['-severity', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='software_po_organiz_fb923e_idx')],
            },
        ),
    ]
