# Generated by Django 6.0.4 on 2026-05-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_vulnerability'),
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Filter spec — see AssetGroup docstring for keys.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_groups', to='core.organization')),
            ],
            options={
                'db_table': 'asset_groups',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
