# Generated by Django 6.0.4 on 2026-05-05 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_asset_config_monitored'),
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('firmware_update', 'Firmware update available'), ('drift', 'Configuration drift'), ('vulnerability', 'Vulnerability patch'), ('lifecycle', 'Lifecycle replacement'), ('health', 'Health score regression')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('summary', models.CharField(help_text='Plain-text recommendation — "Patch Apache Log4j (CVE-2021-44228) on srv01 — fixed in 2.17.0"', max_length=400)),
                ('rationale', models.TextField(blank=True, help_text='Why we suggested it; future LLM versions put their reasoning here.')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Optional structured details: CVE id, fixed version, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_ticket_id', models.PositiveIntegerField(blank=True, help_text='Pk of the PSA Ticket spawned by accept().', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_suggestions', to='assets.asset')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': 'asset_remediation_suggestions',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['status', '-generated_at'], name='asset_remed_status_9f5169_idx'), models.Index(fields=['asset', 'status'], name='asset_remed_asset_i_b7db9e_idx')],
            },
        ),
    ]
