# Generated by Django 6.0.1 on 2026-01-11 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_organization_city_organization_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('itglue', 'IT Glue'), ('hudu', 'Hudu')], max_length=20)),
                ('source_url', models.URLField(help_text='API endpoint URL (e.g., https://api.itglue.com or https://demo.hudu.com)')),
                ('source_api_key', models.CharField(help_text='API key for authentication', max_length=500)),
                ('import_assets', models.BooleanField(default=True, help_text='Import assets/configuration items')),
                ('import_passwords', models.BooleanField(default=True, help_text='Import passwords')),
                ('import_documents', models.BooleanField(default=True, help_text='Import documents/articles')),
                ('import_contacts', models.BooleanField(default=False, help_text='Import contacts')),
                ('import_locations', models.BooleanField(default=False, help_text='Import locations')),
                ('import_networks', models.BooleanField(default=False, help_text='Import networks')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Total items to import')),
                ('items_imported', models.PositiveIntegerField(default=0, help_text='Successfully imported items')),
                ('items_skipped', models.PositiveIntegerField(default=0, help_text='Skipped items (already exist)')),
                ('items_failed', models.PositiveIntegerField(default=0, help_text='Failed items')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('import_log', models.TextField(blank=True, help_text='Detailed import log')),
                ('dry_run', models.BooleanField(default=True, help_text='Preview import without saving data')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs_started', to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(help_text='Organization to import data into', on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.organization')),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(help_text='Source object type (asset, password, document, etc.)', max_length=50)),
                ('source_id', models.CharField(help_text='ID in source system', max_length=100)),
                ('target_model', models.CharField(help_text='Django model name (Asset, Password, etc.)', max_length=100)),
                ('target_id', models.PositiveIntegerField(help_text='ID in Client St0r')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='imports.importjob')),
            ],
            options={
                'db_table': 'import_mappings',
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='import_jobs_status_46b7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['source_type'], name='import_jobs_source__9818a7_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['target_organization'], name='import_jobs_target__84a6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='importmapping',
            index=models.Index(fields=['source_type', 'source_id'], name='import_mapp_source__0d09d2_idx'),
        ),
        migrations.AddIndex(
            model_name='importmapping',
            index=models.Index(fields=['target_model', 'target_id'], name='import_mapp_target__d5d7de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importmapping',
            unique_together={('import_job', 'source_type', 'source_id')},
        ),
    ]
