# Generated by Django 6.0.4 on 2026-04-28 14:21

from django.db import migrations, models


# Per-system-role AI permission defaults — see psa/ROADMAP.md row matrix.
# Keys are template names (matches RoleTemplate.name where is_system_template=True).
SYSTEM_TEMPLATE_AI_DEFAULTS = {
    'Owner': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': True, 'psa_ai_send_high_risk': True,
        'psa_ai_approve_reply': True, 'psa_ai_apply_low_risk': True,
        'psa_ai_apply_high_risk': True, 'psa_ai_approve_action': True,
        'psa_ai_run_script': True, 'psa_ai_create_workflow': True,
        'psa_ai_billing': True, 'psa_ai_admin': True,
    },
    'Administrator': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': True, 'psa_ai_send_high_risk': True,
        'psa_ai_approve_reply': True, 'psa_ai_apply_low_risk': True,
        'psa_ai_apply_high_risk': True, 'psa_ai_approve_action': True,
        'psa_ai_run_script': True, 'psa_ai_create_workflow': True,
        'psa_ai_billing': True, 'psa_ai_admin': False,
    },
    'Editor': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': True, 'psa_ai_send_high_risk': True,
        'psa_ai_approve_reply': True, 'psa_ai_apply_low_risk': True,
        'psa_ai_apply_high_risk': True, 'psa_ai_approve_action': False,
        'psa_ai_run_script': True, 'psa_ai_create_workflow': True,
        'psa_ai_billing': False, 'psa_ai_admin': False,
    },
    'Help Desk': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': True, 'psa_ai_send_high_risk': False,
        'psa_ai_approve_reply': False, 'psa_ai_apply_low_risk': True,
        'psa_ai_apply_high_risk': False, 'psa_ai_approve_action': False,
        'psa_ai_run_script': False, 'psa_ai_create_workflow': False,
        'psa_ai_billing': False, 'psa_ai_admin': False,
    },
    'IT Manager': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': True, 'psa_ai_send_high_risk': True,
        'psa_ai_approve_reply': True, 'psa_ai_apply_low_risk': True,
        'psa_ai_apply_high_risk': True, 'psa_ai_approve_action': False,
        'psa_ai_run_script': True, 'psa_ai_create_workflow': True,
        'psa_ai_billing': False, 'psa_ai_admin': False,
    },
    'Documentation Writer': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': False, 'psa_ai_send_high_risk': False,
        'psa_ai_approve_reply': False, 'psa_ai_apply_low_risk': False,
        'psa_ai_apply_high_risk': False, 'psa_ai_approve_action': False,
        'psa_ai_run_script': False, 'psa_ai_create_workflow': False,
        'psa_ai_billing': False, 'psa_ai_admin': False,
    },
    'Read-Only': {
        'psa_ai_view': True, 'psa_ai_send_low_risk': False, 'psa_ai_send_high_risk': False,
        'psa_ai_approve_reply': False, 'psa_ai_apply_low_risk': False,
        'psa_ai_apply_high_risk': False, 'psa_ai_approve_action': False,
        'psa_ai_run_script': False, 'psa_ai_create_workflow': False,
        'psa_ai_billing': False, 'psa_ai_admin': False,
    },
}


def backfill_system_templates(apps, schema_editor):
    """Apply role-matrix defaults to existing system RoleTemplate rows."""
    RoleTemplate = apps.get_model('accounts', 'RoleTemplate')
    for name, flags in SYSTEM_TEMPLATE_AI_DEFAULTS.items():
        rows = RoleTemplate.objects.filter(name=name, is_system_template=True,
                                           organization__isnull=True)
        for row in rows:
            for k, v in flags.items():
                setattr(row, k, v)
            row.save(update_fields=list(flags.keys()))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_preferred_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_admin',
            field=models.BooleanField(default=False, help_text='Configure AI (model, threshold, allow/blocklist, voice)'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_apply_high_risk',
            field=models.BooleanField(default=False, help_text='Apply medium- or high-risk AI actions (state changes, assignment)'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_apply_low_risk',
            field=models.BooleanField(default=False, help_text='Apply low-risk AI actions (e.g. set priority, add internal note)'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_approve_action',
            field=models.BooleanField(default=False, help_text="Approve another user's pending AI action"),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_approve_reply',
            field=models.BooleanField(default=False, help_text="Approve another user's pending AI reply"),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_billing',
            field=models.BooleanField(default=False, help_text='Modify financial fields (invoiced amount, contract usage) via AI'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_create_workflow',
            field=models.BooleanField(default=False, help_text='Create or assign a workflow from an AI suggestion'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_run_script',
            field=models.BooleanField(default=False, help_text='Run an AI-suggested RMM script against an asset'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_send_high_risk',
            field=models.BooleanField(default=False, help_text='Send medium- or high-risk AI replies (requires admin in most orgs)'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_send_low_risk',
            field=models.BooleanField(default=False, help_text='Send low-risk AI replies as public ticket comments'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_view',
            field=models.BooleanField(default=True, help_text='View AI suggestions and the AI inbox'),
        ),
        migrations.RunPython(backfill_system_templates, noop_reverse),
    ]
