# Generated by Django 6.0.4 on 2026-04-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_roletemplate_psa_ai_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text='Org Admin: lets a portal user manage which other members of the same organization can access vault items shared in `org_admin_managed` mode. Independent of the staff Admin role; only meaningful for client portal users.'),
        ),
    ]
