# Generated by Django 6.0.4 on 2026-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_roletemplate_psa_ai_request_triage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_assigned_email',
            field=models.BooleanField(default=True, help_text='Send me an email when a PSA ticket is assigned to me.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_assigned_sms',
            field=models.BooleanField(default=False, help_text='Text my UserProfile.phone when a PSA ticket is assigned to me. Requires SMS to be configured globally and a phone number on this profile.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_scheduled_email',
            field=models.BooleanField(default=True, help_text='Send me an email when an assigned ticket gets a due date (or a new one).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_scheduled_sms',
            field=models.BooleanField(default=False, help_text='Text me when an assigned ticket gets a due date.'),
        ),
    ]
