# Generated by Django 6.0.4 on 2026-04-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_roletemplate_kb_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='billing_record_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='billing_send_invoices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='billing_view_aging',
            field=models.BooleanField(default=False, help_text='See the cross-client aging report.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='billing_view_invoices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='reports_manage_dashboards',
            field=models.BooleanField(default=False, help_text='Create / edit / delete dashboards + widgets.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='reports_manage_scheduled',
            field=models.BooleanField(default=False, help_text='Configure scheduled reports.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='reports_view_capacity',
            field=models.BooleanField(default=False, help_text='Capacity / utilization report — exposes target hours + realization % per tech across the team.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='reports_view_dashboards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='reports_view_financial',
            field=models.BooleanField(default=False, help_text='Profitability, effective hourly rate, revenue leakage, margin analytics — surfaces revenue + cost numbers.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='reports_view_sla',
            field=models.BooleanField(default=False, help_text="SLA trend report. Defaults off because techs don't need it."),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='resourcing_approve_leave',
            field=models.BooleanField(default=False, help_text='Approve / deny LeaveRequest.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='resourcing_manage_cost_rates',
            field=models.BooleanField(default=False, help_text='Edit per-tech loaded $/hr rates. Drives all profitability math.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='resourcing_manage_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='resourcing_view_team',
            field=models.BooleanField(default=False, help_text='See the staff tech roster + cost rates list.'),
        ),
    ]
