# Generated by Django 6.0.4 on 2026-04-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_roletemplate_crm_create_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='change_approve_cab',
            field=models.BooleanField(default=False, help_text='Sit on the CAB and vote on changes.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='change_create',
            field=models.BooleanField(default=True, help_text='Submit a change request for CAB review.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='change_implement',
            field=models.BooleanField(default=False, help_text='Move an approved change into Implementing.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='change_view',
            field=models.BooleanField(default=True),
        ),
    ]
