# Generated by Django 6.0.4 on 2026-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_roletemplate_change_approve_cab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='problem_assign',
            field=models.BooleanField(default=False, help_text='Assign problems to investigators / reassign owners.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='problem_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='problem_resolve',
            field=models.BooleanField(default=False, help_text='Move a problem to resolved/closed status.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='problem_view',
            field=models.BooleanField(default=True),
        ),
    ]
