# Generated by Django 6.0.4 on 2026-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_roletemplate_vault_manage_access_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='catalog_approve_change',
            field=models.BooleanField(default=False, help_text='Approve / reject ServiceCatalogChange proposals.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='catalog_propose_change',
            field=models.BooleanField(default=True, help_text='Propose edits to a service catalog item that requires approval.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='release_freeze',
            field=models.BooleanField(default=False, help_text='Flip a release to frozen/completed/rolled_back.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='release_manage',
            field=models.BooleanField(default=False, help_text='Create / edit release windows + bundle changes.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='release_view',
            field=models.BooleanField(default=True),
        ),
    ]
