# Generated by Django 6.0.4 on 2026-04-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_roletemplate_outsourcing_share_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='security_alerts_acknowledge',
            field=models.BooleanField(default=False, help_text='Acknowledge / dismiss / resolve alerts and convert to PSA tickets.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='security_alerts_create_rules',
            field=models.BooleanField(default=False, help_text='Create / edit / delete auto-ticket rules + suppression windows.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='security_alerts_manage_connections',
            field=models.BooleanField(default=False, help_text='Create / edit / delete EDR / AV / firewall connections.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='security_alerts_view',
            field=models.BooleanField(default=True, help_text='View the security alert triage list and alert detail.'),
        ),
    ]
