# Generated by Django 6.0.4 on 2026-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_roletemplate_security_alerts_acknowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quick_actions_config',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of quick-action keys the user wants on their dashboard. Empty = use defaults.'),
        ),
    ]
