# Generated by Django 6.0.4 on 2026-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_quick_actions_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portal_notify_csat_invite',
            field=models.BooleanField(default=True, help_text='Email me a CSAT survey link when one of my tickets is resolved.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portal_notify_status_change',
            field=models.BooleanField(default=True, help_text='Send me an email when one of my tickets changes status.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portal_notify_ticket_reply',
            field=models.BooleanField(default=True, help_text='Send me an email when a staff member replies to one of my tickets.'),
        ),
    ]
