# Generated by Django 6.0.4 on 2026-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_userprofile_portal_notify_csat_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portal_notify_sms_status_change',
            field=models.BooleanField(default=False, help_text='v3.17.238: text my profile phone when one of my tickets changes status. Requires SMS to be enabled globally and a phone number on file. Off by default since SMS often costs.'),
        ),
    ]
