# Generated by Django 6.0.4 on 2026-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userprofile_portal_notify_sms_status_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='vault_extension_offline_cache',
            field=models.BooleanField(default=False, help_text='Allow the browser extension to bulk-sync the visible vault as encrypted blobs for offline access.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='vault_extension_use',
            field=models.BooleanField(default=False, help_text='Use the browser extension (autofill / TOTP / reveal via Authorization: Bearer token).'),
        ),
    ]
