# Generated by Django 6.0.4 on 2026-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_roletemplate_vault_extension_offline_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_assign',
            field=models.BooleanField(default=False, help_text='Assign a ticket to another user (re-assignment).'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_close',
            field=models.BooleanField(default=True, help_text='Move a ticket to a terminal status (resolved / closed).'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_create',
            field=models.BooleanField(default=True, help_text='File new tickets.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_delete',
            field=models.BooleanField(default=False, help_text='Hard-delete a ticket.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_edit',
            field=models.BooleanField(default=True, help_text='Edit ticket subject / description / status / priority.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_view',
            field=models.BooleanField(default=True, help_text='View tickets in the PSA / mobile surfaces.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tickets_view_all',
            field=models.BooleanField(default=False, help_text='View tickets across all organizations (not just tickets in orgs the user is a member of).'),
        ),
    ]
