# Generated by Django 6.0.4 on 2026-05-07 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        ('locations', '0008_add_wan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSiteGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('radius', 'Radius (lat/lon + meters)'), ('polygon', 'Polygon (list of lat/lon vertices)')], default='radius', max_length=12)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('polygon_json', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='core.organization')),
            ],
            options={
                'verbose_name': 'Client site geofence',
                'verbose_name_plural': 'Client site geofences',
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.PositiveIntegerField(default=0, help_text='Reported accuracy radius in meters')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('mobile', 'Mobile app'), ('web', 'Web browser')], default='mobile', max_length=12)),
                ('retention_until', models.DateField(db_index=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician GPS ping',
                'verbose_name_plural': 'Technician GPS pings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tech', 'timestamp'], name='field_ops_t_tech_id_61fecc_idx')],
            },
        ),
    ]
