# Generated by Django 6.0.4 on 2026-05-07 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('core', '0060_organization_exposure_score_and_more'),
        ('field_ops', '0001_initial'),
        ('locations', '0008_add_wan_model'),
        ('psa', '0056_ticketcomment_voice_meta_tickettimeentry_end_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authtoken.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile device',
                'verbose_name_plural': 'Mobile devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='field_ops_m_user_id_30540c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeclockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('clocked_out_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('mobile', 'Mobile app'), ('web', 'Web browser'), ('manual', 'Manual entry')], default='mobile', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derived_time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='psa.tickettimeentry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeclock_entries', to='locations.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeclock_entries', to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeclock_entries', to='psa.project')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeclock_entries', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeclock_entries', to='psa.ticket')),
            ],
            options={
                'verbose_name': 'Timeclock entry',
                'verbose_name_plural': 'Timeclock entries',
                'ordering': ['-clocked_in_at'],
                'indexes': [models.Index(fields=['tech', '-clocked_in_at'], name='field_ops_t_tech_id_31ace9_idx'), models.Index(fields=['organization', '-clocked_in_at'], name='field_ops_t_organiz_76298b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clocked_out_at__isnull', True)), fields=('tech',), name='field_ops_one_open_timeclock_per_tech')],
            },
        ),
    ]
