# Generated by Django 6.0.4 on 2026-05-07 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        ('field_ops', '0004_autotimepreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFieldOpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geofence_only_mode', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_ops_settings', to='core.organization')),
            ],
            options={
                'verbose_name': 'Org Field Ops settings',
                'verbose_name_plural': 'Org Field Ops settings',
            },
        ),
        migrations.CreateModel(
            name='GeofenceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='field_ops.clientsitegeofence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['user', '-entered_at'], name='field_ops_g_user_id_b1e9f7_idx'), models.Index(fields=['geofence', '-entered_at'], name='field_ops_g_geofenc_ca557a_idx')],
            },
        ),
    ]
