# Generated by Django 6.0.2 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_add_file_upload_to_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='diagram_type',
            field=models.CharField(choices=[('erd', 'Entity Relationship Diagram'), ('floorplan', 'Floor Plan'), ('flowchart', 'Flowchart'), ('network', 'Network Diagram'), ('org', 'Organizational Chart'), ('other', 'Other'), ('process', 'Process Flow'), ('rack', 'Rack Layout'), ('architecture', 'System Architecture')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='diagramannotation',
            name='annotation_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('issue', 'Issue'), ('note', 'Note'), ('suggestion', 'Suggestion')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentflag',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow')], default='yellow', max_length=20),
        ),
    ]
