# Generated by Django 6.0.4 on 2026-04-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_add_system_package_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_client_visible',
            field=models.BooleanField(default=False, help_text='Visible to clients in the customer portal /portal/kb/ — global articles surface to every portal user, org-scoped articles only to that client.'),
        ),
    ]
