# Generated by Django 6.0.4 on 2026-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_document_is_client_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_featured_in_portal',
            field=models.BooleanField(default=False, help_text='v3.17.234: pin this article to the top of the customer portal KB list. Useful for "How to file a support ticket", common FAQs, etc.'),
        ),
        migrations.AddField(
            model_name='document',
            name='portal_view_count',
            field=models.PositiveIntegerField(default=0, help_text='v3.17.234: incremented every time a portal user opens this article. Used to surface popular content + track engagement.'),
        ),
    ]
