# Generated by Django 6.0.4 on 2026-04-29 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcing', '0002_billabletarget_holiday_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField(help_text='Rate applies from this date forward (inclusive). The most recent effective_from <= a given report date wins.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_cost_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resourcing_tech_cost_rates',
                'ordering': ['-effective_from', 'user__username'],
                'indexes': [models.Index(fields=['user', '-effective_from'], name='resourcing__user_id_5b6db8_idx')],
                'unique_together': {('user', 'effective_from')},
            },
        ),
    ]
