# Generated by Django 5.0 on 2026-03-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0036_add_inventory_scheduling_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code, e.g. #ff0000', max_length=7)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='inventory_categories',
                    to='core.organization',
                )),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='inventory_locations',
                    to='core.organization',
                )),
            ],
            options={
                'verbose_name': 'Inventory Location',
                'verbose_name_plural': 'Inventory Locations',
                'db_table': 'inventory_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit / internal part number', max_length=100)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100)),
                ('item_type', models.CharField(
                    choices=[
                        ('spare_part', 'Spare Part'),
                        ('hardware', 'Hardware'),
                        ('consumable', 'Consumable'),
                        ('tool', 'Tool'),
                        ('cable', 'Cable'),
                        ('license', 'License'),
                        ('other', 'Other'),
                    ],
                    default='other',
                    max_length=20,
                )),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, default='ea', help_text='Unit of measure (ea, box, pack, etc.)', max_length=50)),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum stock level before reorder alert')),
                ('reorder_quantity', models.IntegerField(default=0, help_text='Quantity to reorder when low')),
                ('reorder_link', models.URLField(blank=True, help_text='URL to purchase / reorder this item')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('category', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='items',
                    to='inventory.inventorycategory',
                )),
                ('storage_location', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='items',
                    to='inventory.inventorylocation',
                )),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='inventory_items',
                    to='core.organization',
                )),
                ('tags', models.ManyToManyField(blank=True, related_name='inventory_items', to='core.tag')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(
                    choices=[
                        ('stock_in', 'Stock In'),
                        ('stock_out', 'Stock Out'),
                        ('adjustment', 'Adjustment'),
                        ('transfer', 'Transfer'),
                    ],
                    max_length=20,
                )),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for removals')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after this transaction')),
                ('notes', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, help_text='Reference number, ticket, PO, etc.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='transactions',
                    to='inventory.inventoryitem',
                )),
                ('performed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='inventory_transactions',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
