# Generated by Django 6.0.4 on 2026-05-02 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
        ('reports', '0002_scheduledreport_output_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Free-text label shown in the wallboard list and as the page title.', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('refresh_seconds', models.PositiveIntegerField(default=60, help_text='How often each widget refreshes on the rendered page. Set to 0 to disable auto-refresh.')),
                ('rotate_seconds', models.PositiveIntegerField(default=0, help_text='If > 0, the rotation view will move to the next wallboard after this many seconds. 0 means rotation skips this board.')),
                ('is_active', models.BooleanField(default=True, help_text='Off ⇒ board still saves but is hidden from rotation + the list view.')),
                ('order', models.PositiveIntegerField(default=100, help_text='Rotation position. Lower fires first; ties broken by name.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallboards_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallboards', to='core.organization')),
            ],
            options={
                'db_table': 'reports_wallboards',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WallboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('metric', 'Metric Card'), ('chart_line', 'Line Chart'), ('chart_bar', 'Bar Chart'), ('chart_pie', 'Pie Chart'), ('table', 'Data Table'), ('list', 'List View'), ('calendar', 'Calendar'), ('map', 'Map')], max_length=20)),
                ('data_source', models.CharField(help_text='Key from reports.widget_sources.REGISTRY (e.g. "open_tickets_count", "revenue_trend_30d").', max_length=100)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Widget-specific config (color, sub-title, etc.)')),
                ('position', models.JSONField(default=dict, help_text='12-column grid position as {x, y, width, height}.')),
                ('order', models.PositiveIntegerField(default=100, help_text='Render order within the wallboard. Lower first.')),
                ('refresh_seconds', models.PositiveIntegerField(blank=True, help_text='Per-widget refresh override. NULL ⇒ inherit from the wallboard.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.wallboard')),
            ],
            options={
                'db_table': 'reports_wallboard_widgets',
                'ordering': ['wallboard', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='wallboard',
            index=models.Index(fields=['organization', 'is_active', 'order'], name='reports_wal_organiz_877b7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallboard',
            unique_together={('organization', 'name')},
        ),
    ]
