# Generated by Django 6.0.4 on 2026-04-28 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('integrations', '0021_fix_unifi_mode_column'),
        ('psa', '0004_watchers_and_canned_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('action', 'Action')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('review_state', models.CharField(choices=[('draft', 'Drafted by AI — awaiting tech review'), ('pending_review', 'Awaiting senior approval'), ('approved', 'Approved (and applied)'), ('rejected', 'Rejected by reviewer'), ('expired', 'Expired before action'), ('superseded', 'Replaced by a newer suggestion'), ('failed', 'Generation failed'), ('blocked', 'Blocked by safety filter')], default='draft', max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('suggested_body', models.TextField(blank=True)),
                ('final_body', models.TextField(blank=True, help_text='What was actually sent (after edits)')),
                ('action_type', models.CharField(blank=True, max_length=50)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_review_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('native_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='psa.ticket')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='core.organization')),
                ('psa_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='integrations.psaticket')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_ai_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_logs', to='core.organization')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='psa_ai.aisuggestion')),
            ],
            options={
                'db_table': 'psa_ai_action_logs',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('org', 'Organization'), ('user', 'User')], max_length=10)),
                ('day', models.DateField(db_index=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('generations', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_buckets', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_buckets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_ai_usage_buckets',
            },
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['organization', 'review_state', '-created_at'], name='psa_ai_sugg_organiz_6497ed_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['native_ticket', '-created_at'], name='psa_ai_sugg_native__8495f7_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['psa_ticket', '-created_at'], name='psa_ai_sugg_psa_tic_795a28_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['requested_by', '-created_at'], name='psa_ai_sugg_request_e62224_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagebucket',
            index=models.Index(fields=['scope', 'day'], name='psa_ai_usag_scope_4afe02_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagebucket',
            index=models.Index(fields=['organization', 'day'], name='psa_ai_usag_organiz_65a450_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagebucket',
            index=models.Index(fields=['user', 'day'], name='psa_ai_usag_user_id_6382f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiusagebucket',
            unique_together={('scope', 'organization', 'user', 'day')},
        ),
    ]
