# Generated by Django 6.0.4 on 2026-04-30 02:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsetting_crm_enabled'),
        ('crm', '0002_lead_score_commissionrule_commission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('note', 'Note'), ('proposal_sent', 'Proposal Sent'), ('contract_signed', 'Contract Signed'), ('inbound', 'Inbound (auto-captured)'), ('other', 'Other')], default='note', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity actually happened (manual entry can backdate).')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Optional — for calls / meetings.', null=True)),
                ('outcome', models.CharField(blank=True, help_text='Free-form: "Booked discovery call next week"', max_length=200)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('web_form', 'Web Form'), ('imap', 'Email (IMAP)'), ('api', 'REST API')], default='manual', max_length=40)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='For inbound activities — store the raw email/form data for audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_sales_activities_client', to='core.organization')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity')),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the activity log.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_sales_activities_msp', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales activities',
                'db_table': 'crm_sales_activities',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='crm_sales_a_organiz_a5fc1d_idx'), models.Index(fields=['lead', '-occurred_at'], name='crm_sales_a_lead_id_d5315d_idx'), models.Index(fields=['opportunity', '-occurred_at'], name='crm_sales_a_opportu_37076e_idx'), models.Index(fields=['client_org', '-occurred_at'], name='crm_sales_a_client__328c4e_idx')],
            },
        ),
    ]
