# Generated by Django 6.0.2 on 2026-02-19 16:04

from django.db import migrations, models
import django.db.models.deletion


def migrate_connection_to_generic(apps, schema_editor):
    """
    Migrate data from old connection ForeignKey to new GenericForeignKey.
    """
    ExternalObjectMap = apps.get_model('integrations', 'ExternalObjectMap')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType for PSAConnection
    psa_connection_ct = ContentType.objects.get(
        app_label='integrations',
        model='psaconnection'
    )

    # Update all existing records to use the GenericForeignKey
    for obj in ExternalObjectMap.objects.all():
        if obj.connection_old_id:  # connection_old is the old ForeignKey
            obj.connection_type = psa_connection_ct
            obj.connection_id = obj.connection_old_id
            obj.save(update_fields=['connection_type', 'connection_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_remove_rmmdevice_lat_lon_idx_safe'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Step 1: Rename old connection field to connection_old
        migrations.RenameField(
            model_name='externalobjectmap',
            old_name='connection',
            new_name='connection_old',
        ),

        # Step 2: Add new GenericForeignKey fields
        migrations.AddField(
            model_name='externalobjectmap',
            name='connection_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='externalobjectmap',
            name='connection_id',
            field=models.PositiveIntegerField(null=True),
        ),

        # Step 3: Migrate data from old to new fields
        migrations.RunPython(
            migrate_connection_to_generic,
            reverse_code=migrations.RunPython.noop
        ),

        # Step 4: Make new fields non-nullable
        migrations.AlterField(
            model_name='externalobjectmap',
            name='connection_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AlterField(
            model_name='externalobjectmap',
            name='connection_id',
            field=models.PositiveIntegerField(),
        ),

        # Step 5: Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='externalobjectmap',
            unique_together=set(),
        ),

        # Step 6: Remove old connection field
        migrations.RemoveField(
            model_name='externalobjectmap',
            name='connection_old',
        ),

        # Step 7: Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name='externalobjectmap',
            unique_together={('connection_type', 'connection_id', 'external_type', 'external_id')},
        ),

        # Step 8: Add index for GenericForeignKey
        migrations.AddIndex(
            model_name='externalobjectmap',
            index=models.Index(fields=['connection_type', 'connection_id'], name='ext_obj_map_conn_idx'),
        ),
    ]
