# Generated by Django 6.0.2 on 2026-02-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_convert_to_generic_connection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rmmdevice',
            name='rmm_devices_lat_lon_idx',
        ),
        migrations.RenameIndex(
            model_name='externalobjectmap',
            new_name='external_ob_connect_9c6dfd_idx',
            old_name='ext_obj_map_conn_idx',
        ),
    ]
