# Generated by Django 6.0.4 on 2026-05-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        ('integrations', '0026_taxconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('dell', 'Dell TechDirect Warranty'), ('hpe', 'HPE iLO Warranty'), ('lenovo', 'Lenovo Support Warranty'), ('manual', 'Manual / external (no automation)')], default='manual', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_lookup_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_connections', to='core.organization')),
            ],
            options={
                'db_table': 'warranty_connections',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
