# Generated by Django 6.0.7 on 2026-07-19 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_betatesterrequest_source_install'),
        ('integrations', '0027_warrantyconnection'),
        ('locations', '0008_add_wan_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='psacompany',
            name='customer_type',
            field=models.CharField(blank=True, help_text='Customer type as configured in the PSA', max_length=100),
        ),
        migrations.AddField(
            model_name='psacompany',
            name='is_fully_managed',
            field=models.BooleanField(default=False, help_text='Client has at least one recurring invoice in the PSA'),
        ),
        migrations.AddField(
            model_name='psacompany',
            name='notes',
            field=models.TextField(blank=True, help_text='Client notes from the PSA'),
        ),
        migrations.AddField(
            model_name='psacompany',
            name='recurring_invoice_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psacompany',
            name='recurring_invoice_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of recurring invoice amounts per billing cycle', max_digits=12),
        ),
        migrations.AddField(
            model_name='psaconnection',
            name='sync_contracts',
            field=models.BooleanField(default=True, help_text='Sync contracts (providers that support it)'),
        ),
        migrations.AddField(
            model_name='psaconnection',
            name='sync_recurring_invoices',
            field=models.BooleanField(default=True, help_text='Sync recurring invoices and derive the fully-managed flag'),
        ),
        migrations.AddField(
            model_name='psaconnection',
            name='sync_sites',
            field=models.BooleanField(default=True, help_text='Sync sites/locations (providers that support it)'),
        ),
        migrations.CreateModel(
            name='PSAContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('ref', models.CharField(blank=True, help_text='Contract reference in the PSA', max_length=255)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('billing_period', models.CharField(blank=True, max_length=50)),
                ('period_charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='integrations.psacompany')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_contracts', to='integrations.psaconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_contracts', to='core.organization')),
            ],
            options={
                'db_table': 'psa_synced_contracts',
                'ordering': ['ref'],
                'indexes': [models.Index(fields=['organization', 'ref'], name='psa_synced__organiz_d30659_idx')],
                'unique_together': {('connection', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PSARecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('contract_ref', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('next_creation_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoices', to='integrations.psacompany')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='integrations.psaconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_recurring_invoices', to='core.organization')),
            ],
            options={
                'db_table': 'psa_recurring_invoices',
                'ordering': ['-total'],
                'indexes': [models.Index(fields=['organization'], name='psa_recurri_organiz_0c6e79_idx')],
                'unique_together': {('connection', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PSASite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, help_text='Delivery/physical address from the PSA')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_invoice_site', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='integrations.psacompany')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='integrations.psaconnection')),
                ('linked_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_sites', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_sites', to='core.organization')),
            ],
            options={
                'db_table': 'psa_sites',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='psa_sites_organiz_245db9_idx')],
                'unique_together': {('connection', 'external_id')},
            },
        ),
    ]
