# Generated by Django 6.0.2 on 2026-02-21 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Vehicle nickname or identifier', max_length=200)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van'), ('cargo_van', 'Cargo Van'), ('pickup', 'Pickup Truck'), ('other', 'Other')], default='van', max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('color', models.CharField(blank=True, max_length=50)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, verbose_name='VIN')),
                ('license_plate', models.CharField(max_length=20)),
                ('qr_code', models.CharField(blank=True, help_text='QR code for quick vehicle identification (auto-generated or manual entry)', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'In Maintenance'), ('retired', 'Retired')], default='active', max_length=50)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair')], default='good', max_length=50)),
                ('current_mileage', models.IntegerField(default=0, help_text='Current odometer reading', validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expires_at', models.DateField(blank=True, null=True)),
                ('insurance_premium', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly/annual premium amount', max_digits=10, null=True)),
                ('registration_expires_at', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude', max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Currently assigned user/technician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_vehicles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('starting_mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ending_mileage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_date', models.DateField()),
                ('description', models.TextField(help_text='Describe the damage')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('total_loss', 'Total Loss')], default='minor', max_length=50)),
                ('repair_status', models.CharField(choices=[('reported', 'Reported'), ('assessed', 'Assessed'), ('in_repair', 'In Repair'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='reported', max_length=50)),
                ('damage_location', models.CharField(blank=True, help_text="Part of vehicle (e.g., 'Front bumper', 'Driver door')", max_length=200)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_claim_number', models.CharField(blank=True, max_length=100)),
                ('insurance_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('repair_shop', models.CharField(blank=True, max_length=200)),
                ('repair_notes', models.TextField(blank=True)),
                ('condition_before', models.CharField(blank=True, max_length=50)),
                ('condition_after', models.CharField(blank=True, max_length=50)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_damage_reports',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('mileage', models.IntegerField(help_text='Odometer reading at fill-up', validators=[django.core.validators.MinValueValidator(0)])),
                ('gallons', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_per_gallon', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station', models.CharField(blank=True, help_text='Gas station name/location', max_length=200)),
                ('miles_driven', models.IntegerField(blank=True, help_text='Miles since last fill-up', null=True)),
                ('mpg', models.DecimalField(blank=True, decimal_places=2, help_text='Miles per gallon (auto-calculated)', max_digits=5, null=True, verbose_name='MPG')),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_fuel_logs',
                'ordering': ['-date', '-mileage'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Item name (e.g., 'CAT6 Cable', 'RJ45 Connectors')", max_length=200)),
                ('category', models.CharField(blank=True, help_text='Category (Cables, Tools, Hardware, Supplies, etc.)', max_length=100)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (ea, ft, box, etc.)', max_length=50)),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum quantity alert threshold', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('location_in_vehicle', models.CharField(blank=True, help_text="Where stored in vehicle (e.g., 'Toolbox', 'Rear compartment')", max_length=200)),
                ('qr_code', models.CharField(blank=True, help_text='QR code for quick scanning (auto-generated or manual entry)', max_length=200)),
                ('reorder_link', models.URLField(blank=True, help_text='Link to reorder (Amazon, eBay, supplier website, etc.)', max_length=500)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_inventory_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('inspection', 'Inspection'), ('tune_up', 'Tune-up'), ('transmission', 'Transmission Service'), ('coolant', 'Coolant Service'), ('battery', 'Battery Replacement'), ('repair', 'Repair'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('service_date', models.DateField()),
                ('mileage_at_service', models.IntegerField(help_text='Odometer reading at service', validators=[django.core.validators.MinValueValidator(0)])),
                ('performed_by', models.CharField(blank=True, help_text='Mechanic or service center', max_length=200)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_scheduled', models.BooleanField(default=False, help_text='Part of recurring maintenance schedule')),
                ('next_due_mileage', models.IntegerField(blank=True, help_text='Next service due at this mileage', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_due_date', models.DateField(blank=True, help_text='Next service due on this date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_maintenance_records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='servicevehicle',
            index=models.Index(fields=['status'], name='service_veh_status_bf6f16_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevehicle',
            index=models.Index(fields=['license_plate'], name='service_veh_license_9130ce_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevehicle',
            index=models.Index(fields=['assigned_to'], name='service_veh_assigne_3e3d50_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', 'user'], name='vehicle_ass_vehicle_f56066_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['start_date', 'end_date'], name='vehicle_ass_start_d_35fda3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledamagereport',
            index=models.Index(fields=['vehicle', 'repair_status'], name='vehicle_dam_vehicle_0ce966_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledamagereport',
            index=models.Index(fields=['incident_date'], name='vehicle_dam_inciden_59f7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefuellog',
            index=models.Index(fields=['vehicle', 'date'], name='vehicle_fue_vehicle_69a8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefuellog',
            index=models.Index(fields=['date'], name='vehicle_fue_date_b39690_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinventoryitem',
            index=models.Index(fields=['vehicle', 'category'], name='vehicle_inv_vehicle_2a1420_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenancerecord',
            index=models.Index(fields=['vehicle', 'maintenance_type'], name='vehicle_mai_vehicle_be47d3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenancerecord',
            index=models.Index(fields=['service_date'], name='vehicle_mai_service_0ae540_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenancerecord',
            index=models.Index(fields=['next_due_date'], name='vehicle_mai_next_du_7e5987_idx'),
        ),
    ]
