# Generated by Django 6.0.2 on 2026-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_add_rack_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackresource',
            name='port_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Port configuration and connections for patch panels/switches'),
        ),
    ]
