# Generated by Django 6.0.2 on 2026-02-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_add_password_strength_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.URLField(max_length=2000, blank=True),
        ),
    ]
