# Generated by Django 6.0.2 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_increase_url_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('credit_card', 'Credit Card'), ('database', 'Database'), ('email', 'Email Account'), ('ftp', 'FTP/SFTP'), ('network_device', 'Network Device'), ('otp', 'OTP/TOTP (2FA)'), ('other', 'Other'), ('server', 'Server/VPS'), ('software_license', 'Software License'), ('ssh_key', 'SSH Key'), ('vpn', 'VPN'), ('website', 'Website Login'), ('wifi', 'WiFi Network'), ('windows_ad', 'Windows/Active Directory')], default='website', max_length=20),
        ),
    ]
