# Generated by Django 6.0.4 on 2026-04-29 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_add_system_package_scan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='client_access_mode',
            field=models.CharField(choices=[('none', 'Staff only — never shown in client portal'), ('all_org', 'All members of the client organization'), ('specific_users', 'Specific portal users (explicit list)'), ('org_admin_managed', 'Delegated — the client org admin manages access')], default='none', help_text='Who within the client org can see this password in the portal.', max_length=20),
        ),
        migrations.AddField(
            model_name='password',
            name='client_allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Explicit user list — only honoured when access_mode="specific_users".', related_name='vault_passwords_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='password',
            name='client_visible',
            field=models.BooleanField(default=False, help_text='If False, this password never appears in the customer portal — regardless of access mode.'),
        ),
    ]
