# Generated by Django 6.0.4 on 2026-04-30 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
        ('psa', '0026_ticketshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_provider', models.CharField(blank=True, max_length=40)),
                ('match_category', models.CharField(blank=True, max_length=20)),
                ('match_severity_min', models.CharField(blank=True, choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('action', models.CharField(choices=[('create_ticket', 'Create PSA Ticket')], default='create_ticket', max_length=40)),
                ('ticket_queue_id', models.IntegerField(blank=True, null=True)),
                ('ticket_priority_code', models.CharField(blank=True, help_text='P1 / P2 / P3 / P4 / P5 — overrides severity-derived default.', max_length=10)),
                ('suppress_start_hour', models.IntegerField(blank=True, help_text="0-23 in MSP tenant's timezone. Blank = no suppression.", null=True)),
                ('suppress_end_hour', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_client_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alert_rules', to='core.organization')),
                ('ticket_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_alert_rules',
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SecurityVendorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('crowdstrike_falcon', 'CrowdStrike Falcon'), ('sentinelone', 'SentinelOne Singularity'), ('defender', 'Microsoft Defender for Endpoint'), ('sophos_central', 'Sophos Central'), ('huntress', 'Huntress'), ('threatlocker', 'ThreatLocker'), ('bitdefender', 'Bitdefender GravityZone'), ('webroot', 'Webroot'), ('malwarebytes', 'Malwarebytes'), ('eset', 'ESET'), ('fortinet', 'Fortinet FortiGate'), ('palo_alto', 'Palo Alto'), ('sonicwall', 'SonicWall'), ('meraki_mx', 'Cisco Meraki MX'), ('sophos_xg', 'Sophos XG'), ('pfsense', 'pfSense')], max_length=40)),
                ('category', models.CharField(choices=[('edr', 'Endpoint Detection & Response'), ('av', 'Antivirus'), ('firewall', 'Firewall')], max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='AES-GCM-encrypted JSON blob of provider-specific creds (API key / token / username+password / etc).')),
                ('base_url', models.URLField(blank=True, help_text='Provider tenant URL (e.g. https://api.crowdstrike.com).')),
                ('webhook_token', models.CharField(blank=True, help_text='Random token for the inbound webhook URL path.', max_length=64)),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC shared secret for verifying inbound webhook payloads.', max_length=64)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='ok / error / running.', max_length=40)),
                ('last_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(blank=True, help_text='Optionally pin the connection to a specific client. Leave blank for an MSP-wide connection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_vendor_connections_for_client', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the connection.', on_delete=django.db.models.deletion.CASCADE, related_name='security_vendor_connections', to='core.organization')),
            ],
            options={
                'db_table': 'security_vendor_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Vendor-side unique ID — used for dedupe.', max_length=200)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('asset_hint', models.CharField(blank=True, help_text='Free-form hostname / IP / device name from the alert.', max_length=200)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('auto_ticket', models.ForeignKey(blank=True, help_text='If a rule auto-created a ticket from this alert, link to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='psa.ticket')),
                ('client_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts_for_client', to='core.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='core.organization')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security_alerts.securityvendorconnection')),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityvendorconnection',
            index=models.Index(fields=['organization', 'is_active'], name='security_ve_organiz_9dfb42_idx'),
        ),
        migrations.AddIndex(
            model_name='securityvendorconnection',
            index=models.Index(fields=['provider'], name='security_ve_provide_524638_idx'),
        ),
        migrations.AddIndex(
            model_name='securityvendorconnection',
            index=models.Index(fields=['client_org'], name='security_ve_client__58a5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['organization', 'status', '-seen_at'], name='security_al_organiz_9da071_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['client_org', 'severity'], name='security_al_client__79e1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['severity', 'status'], name='security_al_severit_1c570c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityalert',
            unique_together={('connection', 'external_id')},
        ),
    ]
