# Generated by Django 6.0.4 on 2026-05-07 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        ('security_alerts', '0002_alter_securityalert_connection_siemwebhookendpoint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('asset_hint', models.CharField(blank=True, help_text='Hostname / IP / device anchoring the incident — used for auto-correlation of subsequent alerts.', max_length=200)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alerts', models.ManyToManyField(blank=True, help_text='Alerts grouped into this incident.', related_name='incidents', to='security_alerts.securityalert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents_for_client', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the incident.', on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='core.organization')),
            ],
            options={
                'db_table': 'security_incidents',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opened', 'Opened'), ('alert_added', 'Alert added'), ('note', 'Analyst note'), ('status_change', 'Status change'), ('assigned', 'Assigned'), ('acknowledged', 'Acknowledged'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('playbook_action', 'Playbook action'), ('sla_breach', 'SLA breach')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='security_alerts.securityalert')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='security_alerts.securityincident')),
            ],
            options={
                'db_table': 'security_incident_events',
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['organization', 'status', '-opened_at'], name='security_in_organiz_add274_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['client_org', 'severity'], name='security_in_client__eec1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['asset_hint'], name='security_in_asset_h_addfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincidentevent',
            index=models.Index(fields=['incident', 'occurred_at'], name='security_in_inciden_b4944d_idx'),
        ),
    ]
