# Generated by Django 6.0.4 on 2026-05-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        ('security_alerts', '0003_securityincident_securityincidentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncidentSLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Severity bucket the policy applies to.', max_length=20)),
                ('acknowledge_minutes', models.PositiveIntegerField(default=15, help_text='Time-to-acknowledge SLA (minutes from open).')),
                ('contain_minutes', models.PositiveIntegerField(default=60, help_text='Time-to-contain SLA (minutes from open).')),
                ('resolve_minutes', models.PositiveIntegerField(default=240, help_text='Time-to-resolve SLA (minutes from open).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(blank=True, help_text='Optionally pin the policy to one client; blank = MSP-wide for the given severity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organization')),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the policy.', on_delete=django.db.models.deletion.CASCADE, related_name='security_incident_sla_policies', to='core.organization')),
            ],
            options={
                'db_table': 'security_incident_sla_policies',
                'ordering': ['organization', 'severity'],
                'unique_together': {('organization', 'client_org', 'severity')},
            },
        ),
    ]
