# Generated by Django 6.0.4 on 2026-05-07 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        ('security_alerts', '0004_securityincidentslapolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower fires first. Only the first matching playbook runs per incident.')),
                ('match_severity_min', models.CharField(blank=True, choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Match incident.severity >= this. Empty = match-all.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match_client_org', models.ForeignKey(blank=True, help_text='If set, only fires for incidents on this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_playbooks', to='core.organization')),
            ],
            options={
                'db_table': 'remediation_playbooks',
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RemediationPlaybookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10)),
                ('action', models.CharField(choices=[('create_ticket', 'Create PSA ticket'), ('send_email', 'Send email'), ('quarantine_asset_flag', 'Flag asset for quarantine'), ('run_workflow_rule', 'Run PSA workflow rule')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Action-specific config: e.g. {"to": "ops@example.com"} for send_email; {"queue_slug": "soc"} for create_ticket.')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='security_alerts.remediationplaybook')),
            ],
            options={
                'db_table': 'remediation_playbook_steps',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
